### ISSUE TITLE
Re-sync Partial works and W4CZ5369

### ISSUE THREAD

**Issue by karmagongde** [buda-base/library-issues#168]
@TBRC-Travis Hi Travis, In ReadyToProcess, there are several Partial works need to be re-sync. There all are corrected images. 
Derge Kagyur W4CZ5369, I have corrected images order. Now need to be rename and re-sync.

**Comment by eroux** [comment]
@TBRC-JimK @TBRC-Travis is this done? There are people working on the pagination of this work and their work will be wasted if we resync with a different image order...

**Comment by TBRC-Travis** [comment]
@eroux Not yet.  It is ready to sync.  Would you like me to sync it now or would it make sense for Karma to reorder the pages on Incoming and then sync?

**Comment by karmagongde** [comment]
@TBRC-Travis Hi Travis, I have already corrected images order and sent this message on March 22, 2018. It is best to sync now for the people who will use this edition.

**Comment by TBRC-Travis** [comment]
@karmagongde I guess my point was if we sync now and then people reorder the pages again, then we'll have resync another time as well.

**Comment by eroux** [comment]
yes, but let's not reorder the images in the current way after this batch, we'll have a system to reorder images in BUDA without renaming, resyncing, etc.

**Comment by TBRC-Travis** [comment]
well that's a relief.  :)  I'll go ahead and sync these.

**Comment by eroux** [comment]
sorry, to be more clear: please sync the current state now, and then @karmagongde  please let's not touch it again

**Comment by karmagongde** [comment]
Sure, will not touch any images and volume order.

**Comment by TBRC-Travis** [comment]
Images from ReadyToProcess have been synced.

https://www.tbrc.org/#!rid=W4CZ5369

Karma, please confirm the new images are satisfactory and we can close this out.

**Comment by karmagongde** [comment]
Now it is better. earlier 2 pages are off in all the outline pagination. 
Thank you all.

**Comment by eroux** [comment]
ok, thanks a lot!
