### ISSUE TITLE
pulling out missing volume list

### ISSUE THREAD

**Issue by karmagongde** [buda-base/library-issues#200]
@xristy @eroux Hi Chris and Elie,
BDRC is  excepting a volunteer scanner in Cambridge office beginning of the July. I would like to focus on scanning the missing volumes in our Archive so that sets will be completed. Before volunteer join, I want to arrange those books from Harvard Library/UVA library.
Therefore, my request and question is can you able to pull-out all the missing (images) volume in work numbers from our database. For example: W1KG15471 missing vol. no. 2, W23909 missing vol. no. 4, W2DB4589 missing vol. no. 1. If so, please make a list of missing volumes in particular work number. Please let me know.
Thank you,
Karma

**Comment by eroux** [comment]
@karmagongde here's a list of 257 volumes with only 2 pages (the scan request), I believe this corresponds to what you need? Tell me if it doesn't.

[emptyvolumes.zip](https://github.com/BuddhistDigitalResourceCenter/library-issues/files/2128180/emptyvolumes.zip)

**Comment by karmagongde** [comment]
@eroux This is very helpful to find out missing volume with only 2 pages. There are also missing volumes without 2 pages such as in W23909. If these can also pullout with CVS will be very helpful. Many missing volume or incomplete are Periodical Journals. We generated way more scan-request so that we can continue add as journal publish. Thank you.

**Comment by eroux** [comment]
Hmm, them problem with the example you took is that it has an image group ([I5532](https://www.tbrc.org/xmldoc?rid=I5532)) that indicates 0 images. There are 13000+ such image groups in the data, so I don't think it's very helpful to list them. Or is there an additional criteria that I can apply to only select those you're interested in?

**Comment by karmagongde** [comment]
Previous 37000 list is outline nodes page errors not individual volume. You won't see W23909 in query1.csv list. Anyway, I am happy with this list 257 volumes missing images/texts for now.

**Comment by eroux** [comment]
Here's the list I'm talking about:

[queryResults.zip](https://github.com/BuddhistDigitalResourceCenter/library-issues/files/2129057/queryResults.zip)

it contains `W23909` but also all the image groups that are not synced yet. I do not know how to disciminate missing volumes and volumes not synced.

**Comment by karmagongde** [comment]
This list is useful to find missing volume. As I said earlier many no images are from Journal.
Thank you.
