### ISSUE TITLE
duplicate image in W4CZ5369

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#205]
- [ ] in I1KG9128, [I1KG91280035.jpg](https://www.tbrc.org/browser/ImageService?work=W4CZ5369&igroup=I1KG9128&image=35&first=1&last=639&fetchimg=yes) and [I1KG91280036.jpg](https://www.tbrc.org/browser/ImageService?work=W4CZ5369&igroup=I1KG9128&image=36&first=1&last=639&fetchimg=yes) are the same
- [ ] in I1KG9137, I1KG91370019.jpg and I1KG91370021.jpg are the same
- [ ] in I1KG9137, I1KG91370020.jpg and I1KG91370022.jpg are the same
- [ ] in I1KG9209, I1KG92090101.jpg and I1KG92090102.jpg are the same
- [ ] in I1KG9193, I1KG91930166.jpg and I1KG91930167.jpg are the same
- [ ] in I1KG9195, I1KG91950413.jpg and I1KG91950414.jpg are the same
- [ ] in I1KG9221, I1KG92210275.jpg and I1KG92210276.jpg are two scans of the same page, of the same type of quality
- [ ] in I1KG9224, I1KG92240426.jpg and I1KG92240429.jpg are two scans of the same page (there is another duplication in the same area, I wasn't able to spot it)
- [ ] in I1KG9182, I1KG91820103.jpg and I1KG91820104.jpg are two scans of the same page, the first is cropped in a strange way and was certainly meant to be removed
- [ ] in I1KG9141, two scans are missing between I1KG91410387.jpg and I1KG91410388.jpg (compare with other editions), maybe the names of the images could be shifted?
- [ ] in I1KG9225, same situation, two images missing between I1KG92250330.jpg and I1KG92250331.jpg
- [ ] in I1KG9171, I1KG91710147.jpg and I1KG91710149.jpg are the same page but printed twice... it's an error in the printing, not the scan, so we probably can't do much, but maybe it would be worth noting it somewhere... or is there a solution for such cases? maybe having the duplicate prints at the end of the scans?
- [ ] in I0982 (W22084), 09820039.tif and 09820038.tif are two different scans of the same page (or maybe this is an error in the original printing?), but there is also a missing page, so this doesn't shift all images afterwards

**Comment by eroux** [comment]
@karmagongde @TBRC-Travis any thought?

**Comment by karmagongde** [comment]
Hi Elie, I would like to help to recognize images. But, Travis is the right person to asked to fix these issue. Since there is image number, he can remove the duplicate and rename the images and sync at the same time. I will keep the note of missing pages and try to get them.

**Comment by eroux** [comment]
I see, thanks. @TBRC-Travis  would you have time to look at this?

Also @TBRC-JimK  this is an example of something that could be made easier in a future version of the asset manager

**Comment by TBRC-JimK** [comment]
> I see, thanks. @TBRC-Travis would you have time to look at this?
> 
> Also @TBRC-JimK this is an example of something that could be made easier in a future version of the asset manager

Not very likely. As far as the internals are concerned, they are two very different files (in your terms, "two different scans of the same page" . 

`magick identify -verbose ....`
gives us:
[0035.vinfo.txt](https://github.com/buda-base/library-issues/files/2814395/0035.vinfo.txt)
[0036.vinfo.txt](https://github.com/buda-base/library-issues/files/2814397/0036.vinfo.txt)

But the `image-old` folder shows that the images-old/.../I1KG91280035.jpg shows a different image from images/...../I1KG91280035.jpg.

This seems that different portions got syncd at different times.

This is all at TBRCRS3://Archives
/Volumes/Archive/W4CZ5369/images/W4CZ5369-I1KG9128

**Comment by eroux** [comment]
I meant that I think the Asset Manager could give some users (such as the librarians, you, I, etc.) the ability to manually correct this kind of things. Currently the only way is to ping Travis and wait for a few months, possibly years... so having a software or workflow allowing this kind of fixes would be very helpful. Of course if it's automatic it's even better, but manual would be a major improvement already.

**Comment by TBRC-JimK** [comment]
If you can put into requirements “fix” and “this kind of thing,” I’ll see if I can write software to accomplish it.

I cannot see how an automaton could have picked this up – there is no machine level process that identifies these files as different scans of the same page of text.

Only a human eyeball could. And then, once we’ve identified the problem, would you be comfortable hard-coding an algorithm to fix it? We don’t have a rigorous enough file structure to figure out where the replacement image should come from. (In this case, there’s no clear mapping between the Archives folders of CR2 files and the images/WorkNumber-VolumeNumber/VolumeNumber.jpg files either).

If you’re looking for a visual editor to drag and drop images into a sequence, I think that’s what we hope BEAST will do.

If, on the other hand, you’re looking for a test that identifies duplicate or missing file **names**, I’m just finishing that up right now. Maybe I can demo next week, see how many of our archives pass. :O


Jim

**Comment by xristy** [comment]
When there are missing pages do we currently insert page images labeled as missing standing for the missing pp?

Also how will the missing pages be noted (as @karmagongde says above)? The asset manager functionality should add an ```:imagesMissing "75-76, 93, 107"``` in the ```:Volume``` so we search for such info.

**Comment by TBRC-JimK** [comment]
Great input, I’m working on that test right now.
My first pass just stops once a directory fails validation, but I’ll rework it to log all the non-conforming items in a Volume.
Right now, the output is a log file, but once I’ve gotten Audit tool wired into Asset Manager (i.e. once Asset Manager is far enough along to have a persistence layer), those will be noted.

I don’t want any of this diagnostic information in the media folder itself. That should be kept pristine (vierge)
Jim Katz
