### ISSUE TITLE
༸ found in Wylie string

### ISSUE THREAD

**Issue by drupchen** [buda-base/library-issues#207]
I stumbled upon this here:

http://library.bdrc.io/show/bdr:W1KG9580_0231

    ༸rje rgyal ba gnyis pa'i man ngag 'grel pa bzhi sbrags su grags pa'i dbu mjug gnyis kyi sa bcad/bo-x-ewts
    ༸rje rgyal ba gnyis pa'i man ngag 'grel pa bzhi sbrags kyi zin bris bskal bzang dad pa'i shing rta/bo-x-ewts

**Comment by karmagongde** [comment]
I removed the ༧ in Wylie in O1KG9580 outline.
