### ISSUE TITLE
Inversion of scans in the Derge Kanjur

### ISSUE THREAD

**Issue by brunogml** [buda-base/library-issues#214]
Following notice from Kritzer:
"In the  karmapa Derge Saddharmasmṛtyupasthānasūtra, text 287. **Mdo sde sha 176b** (p. 352) and 
**mdo sde ra 176b** (p.352) have been switched".
Please check and fix. 
Thanks

**Comment by eroux** [comment]
thanks for the report!

**Comment by karmagongde** [comment]
Thank you, Kritzer, for informing the switched images in Mdo sde sha 176b (p. 352) and
mdo sde ra 176b (p.352) . I fixed them. I will ask Travis to re-sync so the right images will be on the website. Folder name: W22084-0954 and W22084-0956 
@TBRC-Travis I uploaded the corrected images on partial Folder. Please prioritize them to sync both on images folder and archive folder. Thank you.
