### ISSUE TITLE
person duplicate

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#219]
According to my friend who reported the other issues, P3962 and P0RK695 are duplicates. The source that indicates the fact that they are the same is [གསན་ཡིག་བྱིན་རླབས་རྒྱ་མཚོའི་དཔལ་འབར་ཞེས་བྱ་བ་བཞུགས་སོ](https://www.tbrc.org/#!rid=O00EGS103006%7CO00EGS1030063064$W23892) in W23892. The text refers to "rin po che grags tshul ba" which is a name of P0RK695 but refers to P3962.

**Comment by karmagongde** [comment]
I would like to correct all duplicates authors working with all Librarians. Is there a way to pull all the author's information based on the Primary title. If the Primary title is the same then there is more change of the same author. Those need to be fixed. Primary Name, many of them have the same primary name.
Thank you.

**Comment by eroux** [comment]
Sure, I can send you some excel file with some possible duplicates. In the meantime, it seems P2783 and P2CN21 are the same person. In this case it's relatively obvious (same name, same master, same disciple, etc.)

**Comment by eroux** [comment]
I'm running some queries, these pairs have the same name, and at least one disciple and one master in common, so they have a rather high probability of being duplicates:
- P1GS105233 and  P2JM3
- P0RK479 and P4CZ15075
- P3835 and P8224
- P2JM467 and P696
- P740 and P2JM344
- P1322 and P0RK1794
- P150 and P2584

**Comment by eroux** [comment]
also, these have one name in common and at least one master in common, so they might be worth inspecting... Note that these queries I'm running will miss a lot of duplicates, but we can go step by step...

- [ ] P654 and P659
- [ ] P2JM259 and P8741
- [ ] P1002 and P5287
- [ ] P4900 and P3308
- [ ] P505 and P1862
- [ ] P35 and P4340
- [ ] P2CZ9156 and P483
- [ ] P451 and P1611
- [ ] P6007 and P2JM280
- [ ] P2JM340 and P3JM13
- [ ] P2JM352 and P8LS13216
- [ ] P6306 and P00EGS1017631
- [ ] P8LS12196 and P6744
- [ ] P8435 and P2707
- [ ] P8007 and P3AG53
- [ ] P3AG53 and P7551
- [ ] P1426 and P889
- [ ] P4CZ301808 and P0RK1277
- [ ] P3234 and P1889
- [ ] P290 and P1737
- [ ] P979 and P978
- [ ] P1PD108247 and P925
- [ ] P5890 and P8LS12746
- [ ] P60 and P3874
- [ ] P2009 and P2460
- [ ] P4102 and P9737
- [ ] P4668 and P193
- [ ] P3243 and P3489
- [ ] P193 and P266
- [ ] P266 and P193
- [ ] P0RK1095 and P4CZ15245
- [ ] P5983 and P6011
- [ ] P6507 and P5920
- [ ] P2JM15 and P6986
- [ ] P1094P22
- [ ] P1177 and P166
- [ ] P1615 and P3730
- [ ] P3880 and P1PD96458
- [ ] P1PD96458 and P3880
- [ ] P2156 and P675
- [ ] P414 and P350
- [ ] P350 and P414
- [ ] P10426 and P5290
- [ ] P961 and P811
- [ ] P961 and P808
- [ ] P808 and P811
- [ ] P290 and P4668
- [ ] P3AG30 and P2695
- [ ] P3652 and P5642
- [ ] P5642 and P3652
- [ ] P1746 and P3635
- [ ] P2500 and P2976
- [ ] P9395 and P297
- [ ] P1524 and P4375
- [ ] P1226 and P1865
- [ ] P1865 and P1226
- [ ] P199 and P8LS13323
- [ ] P9432 and P1258
- [ ] P2JM345 and P10497
- [ ] P376 and P166
- [ ] P1205 and P4707
- [ ] P238 and P3170
- [ ] P251 and P8LS12087
- [ ] P8LS12087 and P381
- [ ] P3896 and P0RK746
- [ ] P791 and P793
- [ ] P791 and P780
- [ ] P780 and P791
- [ ] P795 and P791
- [ ] P2273 and P3JT4938
- [ ] P9827 and P6301
- [ ] P10634 and P10631
- [ ] P101 and P84
- [ ] P1614 and P1618
- [ ] P0RK405 and P10172
- [ ] P0RK1114 and P0RK1102
- [ ] P873 and P816
- [ ] P6006 and P8782
- [ ] P1JM507 and P5658
- [ ] P705 and P6066
- [ ] P176 and P3345
- [ ] P741 and P2369
- [ ] P1226 and P505
- [ ] P3505 and P9427
- [ ] P376 and P297
- [ ] P297 and P376
- [ ] P297 and P4483
- [ ] P9221 and P3027
- [ ] P315 and P9403
- [ ] P4483 and P297
- [ ] P3027 and P9221
- [ ] P7031 and P5442
- [ ] P0RK1274 and P10000
- [ ] P10MS14671 and P11MS233
- [ ] P487 and P0RK206
- [ ] P4478 and P3866
- [ ] P2418 and P10475
- [ ] P151 and P2255
- [ ] P2255 and P151
- [ ] P505 and P151
- [ ] P4043 and P636
- [ ] P0RK15 and P10034
- [ ] P0RK431 and P10359
- [ ] P9956 and P0RK431
- [ ] P4512 and P3792
- [ ] P6397 and P6332
- [ ] P805 and P806
- [ ] P1048 and P1072
- [ ] P0RK1434 and P0RK406
- [ ] P8LS13301 and P3799
- [ ] P2259 and P1982
- [ ] P1259 and P3096
- [ ] P2263 and P2264
- [ ] P2AG2 and P434
- [ ] P3133 and P3511
- [ ] P318 and P4CZ15220
- [ ] P268 and P3193
- [ ] P1429 and P3575
- [ ] P1883 and P487
- [ ] P2CZ7940 and P2JM167
- [ ] P4236 and P00EGS1017620
- [ ] P2270 and P478
- [ ] P2104 and P171
- [ ] P4CZ15637 and P0RK659
- [ ] P2JM436 and P2880
- [ ] P2253 and P148
- [ ] P2253 and P4025
- [ ] P780 and P461
- [ ] P1614 and P1056
- [ ] P8LS12008 and P5546
- [ ] P1226 and P0RK1257
- [ ] P0RK196 and P4CZ15358
- [ ] P7401 and P0RK240
- [ ] P0RK301 and P4CZ15237
- [ ] P1865 and P0RK826
- [ ] P649 and P2015
- [ ] P3436 and P1791
- [ ] P6777 and P4155
- [ ] P1746 and P4517
- [ ] P4973 and P4970
- [ ] P307 and P4592
- [ ] P1GS40975 and P0RK1355
- [ ] P2565 and P5678
- [ ] P9945 and P0RK1695
- [ ] P0RK1695 and P9945

**Comment by karmagongde** [comment]
I check some of the list above and most of them are different persons. only they Primary names are same. Would you able to pull out the **Primary Title** of the person? Not the Primary Name.
The P0RK records are more duplicates because Ralf Kramer has created lineage transmission lineage based on thog yig of 'jam mgon a myes zhabs ngag dbang kun dga' bsod nams. He has created a whole new person records even the author already exists in our database (that is back to 2007). 
Also, person record created by Dzongsar Library (P1TLMTGB) are the same issue. 
Anyway, we will look to the P0RK records since some of the records are used in our associated works.
Please do not pull Dzongsar Library's P records with this list. (P1TLMTGB).

**Comment by eroux** [comment]
Ok. Here are the 40 pairs with the same Primary Title:

- [ ] P00EGS1016691 and P00EGS1016749
- [ ] P00EGS1017631 and P6306
- [ ] P0RK389 and P4CZ10541
- [ ] P0RK659 and P4CZ15637
- [ ] P0RK826 and P3630
- [ ] P10274 and P1PD108248
- [ ] P10307 and P2448
- [ ] P1292 and P4127
- [ ] P1303 and P1305
- [ ] P142 and P4566
- [ ] P162 and P3198
- [ ] P1744 and P2501
- [ ] P1GS105233 and P2JM3
- [ ] P1GS60380 and P9827
- [ ] P2033 and P8LS12239
- [ ] P2039 and P2431
- [ ] P2313 and P2574
- [ ] P2782 and P39
- [ ] P2785 and P5494
- [ ] P2CN11072 and P4526
- [ ] P2DB25395 and P8538
- [ ] P2GS1110 and P2GS1118
- [ ] P3772 and P8713
- [ ] P4085 and P8LS12076
- [ ] P4113 and P4951
- [ ] P4418 and P4529
- [ ] P4757 and P6116
- [ ] P5152 and P8LS12489
- [ ] P5172 and P7472
- [ ] P5241 and P5780
- [ ] P5268 and P8LS4338
- [ ] P56 and P9970
- [ ] P5857 and P5867
- [ ] P7009 and P8LS12921
- [ ] P7121 and P9050
- [ ] P8484 and P8985
- [ ] P8532 and P9033
- [ ] P8584 and P8590
- [ ] P8LS4453 and P9811
- [ ] P9280 and P9320

**Comment by karmagongde** [comment]
Pulling out the Primary Title is more effective. In most case, one is duplicate. Some need to check for more information. Thank you.

**Comment by karmagongde** [comment]
I will review the previous list of possible of duplicates too. Is there more list of same Primary Titles to look or this is it? I want to prepare the workflow with librarians.

**Comment by eroux** [comment]
the list contains all the primary title duplicates, there is no other. Thanks a lot!

**Comment by karmagongde** [comment]
Great, I was thinking it will take quite a time to correct them. Right now most of the librarians are on vacation and Holiday-off is coming soon. I will plan to work on this duplication at the beginning of the Year.

**Comment by eroux** [comment]
@karmagongde any update on this one?

**Comment by karmagongde** [comment]
@eroux We reviewed thoroughly all your lists and withdrawn duplicate person record. Many of them are check marked in GitHub list which I looked and others are I copied on the spreadsheet and worked with other librarians. 
https://docs.google.com/spreadsheets/d/1AX7EpSHBwFlSsPzFsD0cKhzPjoOcNV60FLRnokXBcyk/edit#gid=1946632743

**Comment by eroux** [comment]
ok perfect, thanks! (I can't access the spreadsheet but that's ok, I don't need to)

**Comment by eroux** [comment]
Thank a lot for your work, there are still two duplicates that need to be inspected for this issue to be solved:
- [ ] P3962 and P0RK695 (see  གསན་ཡིག་བྱིན་རླབས་རྒྱ་མཚོའི་དཔལ་འབར་ཞེས་བྱ་བ་བཞུགས་སོ in W23892 which refers to "rin po che grags tshul ba" which is a name of P0RK695 but refers to P3962)
- [ ] P2783 and P2CN21

(they are the two initial duplicates that triggered this issue), would you have time to take a look?

**Comment by karmagongde** [comment]
I checked, made the correction, moved all the associated lineage, kinship added the note and withdrawn the duplicate.
withdrawn P3962 and P2CN21.

**Comment by eroux** [comment]
perfect, thanks!
