### ISSUE TITLE
identification of places / persons for EAP import

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#222]
Karma, I'm starting the import of two EAP collections:
- https://eap.bl.uk/project/EAP310
- https://eap.bl.uk/project/EAP039

but most of the names that are used are just phonetics, not proper wylie, so I was wondering if you could give me the RIDs (or create them if they don't exist) for the following places:
   * Thadrak
   * Tshamdrak
   * Nyephug
   * Gangtey

Also, in the URLs above, each place is described with the name of the founder, and some famous abbots, maybe we could record that data?

Thanks

**Comment by karmagongde** [comment]
Are we going to receive digitized images of all these collections?
Thadrak = G3628
Tshamdrak = G382
Nyephug = (hephug) I need to do more research before creating a G# number.
Gangtey = G183

**Comment by eroux** [comment]
Thanks! We are importing their data in the BUDA platform, which will display images on EAP's server (we won't host the images ourselves). RKTs have done some outlines of their Kangyurs but it's not very clear how we can integrate that yet. At some point that should be possible though.

**Comment by eroux** [comment]
I'm thinking of importing a few more EAP archives, Karma, could you identify the places of:
- https://eap.bl.uk/project/EAP570
- https://eap.bl.uk/project/EAP105

such as:
- Drametse
- Ogyen Choling
- Dongkala
- Chizing
- Dodedra
- Phajoding

Encoding the various biographical information would probably be relevant but that's not very important for the import in BUDA...

**Comment by eroux** [comment]
Hi Karma, to be able to finish the EAP import, could you also include the following
- Menrikha temple
- Phurdogkha Temple
- Pumola temple
- Thujedra temple
? thank you!

**Comment by karmagongde** [comment]
Hi Elie,
Here are the G# numbers for EAP import:

- Menrikha temple = G2KG208037
- Phurdogkha Temple = G2KG208038
- Pumola temple = G2KG208039
- Thujedra temple = G2KG208040
- Phurdrup monastery = G2KG208041

Karma

**Comment by eroux** [comment]
Hi Karma,

Thanks a lot!

Best
