### ISSUE TITLE
problems with P4CZ15614

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#225]
(again from my friends studying the Shangpa lineage)

It seems P4CZ15614 is a duplicate of P39. The following:
- https://www.tbrc.org/#!rid=O2MS16391%7CO2MS163914CZ189758$W1PD95844
- https://www.tbrc.org/#!rid=O2MS16391%7CO2MS163914CZ189746$W1PD95844

reference Atulyavajra who was one of khyung po rnal 'byor 's masters.

Also the other texts attributed to P4CZ15614 seem to be misattributed (the recorded colophons don't mention the name):
- https://www.tbrc.org/#!rid=O2MS16391%7CO2MS163914CZ189789$W1PD95844
- https://www.tbrc.org/#!rid=O2MS16391%7CO2MS163914CZ189827$W1PD95844

**Comment by karmagongde** [comment]
Chozin la,
The Outline of Tengyur Pedurma has some issues. Please help to correct them.
Karma

**Comment by karmagongde** [comment]
@eroux With the help of Chozin la, we make corrections.
Karma
