### ISSUE TITLE
problems with the withdrawing process

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#226]
P2814 has been withdrawn in favor of P8LS12967, but

https://www.tbrc.org/#!rid=P2791

still displays both in the `Associated Persons` tab (under the Students header). @xristy could that be a side effect of the web script?

**Comment by xristy** [comment]
I deleted the ref in P2791 to P2814.

Unfortunately there isn't a _functioning_ admin tool for searching for and removing references to withdrawn Persons.

**Comment by eroux** [comment]
ok thanks! I detect and fix this kind of things in the migration so it should be ok, I was mostly worried about a possible error in the automatic duplicate removal script
