### ISSUE TITLE
W4PD5179 no images but is in Products?!

### ISSUE THREAD

**Issue by xristy** [buda-base/library-issues#229]
[W4PD5179](https://www.tbrc.org/#!rid=W4PD5179) is showing that it is in "All Released and Unrestricted Works" and "Wisdom Masters Digital Library 01" but there are no scanned pages?

**Comment by karmagongde** [comment]
The work number W4PD5179 is first published on Sept. 20, 2018 by Paldor. 10 days before he was lay-off from BDRC. I think when he created this work number, he has clone all the information from W21727. We can see the same Catalog Information as well as Product Information. Anyway, we do not have images of W4PD5179 from Paldor.

**Comment by xristy** [comment]
Will you fix or do I need to?

**Comment by karmagongde** [comment]
I will take care of this work number W4PD5179.

**Comment by xristy** [comment]
Thank you

**Comment by karmagongde** [comment]
Hi Chris, I tried to check out W4PD5179 and it is still editing by Paldor. Would you please unlock this work number. and withdraw in favor of W21727. Thank you.
![Screen Shot 2019-03-15 at 2 05 13 PM](https://user-images.githubusercontent.com/19337852/54452631-fc165a80-472b-11e9-9cb2-2e5b01a9d675.png)

**Comment by xristy** [comment]
Lock is cleared

**Comment by karmagongde** [comment]
Took care of it.
