### ISSUE TITLE
examples of Lansta script

### ISSUE THREAD

**Issue by xristy** [buda-base/library-issues#231]
Hi Karma, we're working with the Unicode for Ranjana/Lantsa and need examples from our archive. Élie has started [a document](https://docs.google.com/document/d/1XRdcutBBe6QHe6xo2rXPgj7RuUdR4U2eH9kiTKfKot8/edit) to collect examples that we can forward on to a colleague on the Unicode committee.

If you all know of some examples that you could add to the list that would very helpful. The Unicode support is something we're wanting to help with to support the work in Nepal and can also be useful in eventually recording the Lantsa titling that occurs in some of the Tibetan texts.

Thanks,
Chris

**Comment by karmagongde** [comment]
Hi Chris,
I will tell to Librarians for example. Usually, all the calligraphic texts are under T213.
Best,
Karma
