### ISSUE TITLE
Swapped volumes in Pecing Tengyur

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#234]
The images for Volumes 77 and 81 (bu and dzu) are swapped for the Pecing Tengyur (I couldn't check, it was reported to me by @brunogml from the RKTS project)

**Comment by karmagongde** [comment]
Hi Travis, Elie sent this volume switch issue in W1KG13126, Volume no. 77 W1KG13126-I1KG13246 and Volume no. 81 W1KG13126-I1KG13250 images are switched. There please switch and rename them in all the folders image folder, web, and update eBooks. But keep the scan-request pages as before. Thank you.

**Comment by eroux** [comment]
I'm thinking that another solution could be to change the image groups in the work record without changing the images... @xristy would that work?

**Comment by xristy** [comment]
Yes it should work to indicate in the VolumeMap that the imagegroup currently indicated as volume 77 is declared to be volume 81 and similarly for volume 81 to 77. This requires updating the Work record and the volume number info in the Imagegroup records.

No work for Travis just the librarians need make the change.

**Comment by TBRC-Travis** [comment]
Thanks Chris and Elie.  I think having the librarians use DLMS to update the Imagegroup records when volumes need to be swapped like this is the ideal approach, rather than having to re-jigger all the image artifacts.  Karma, hope this is workable.

**Comment by karmagongde** [comment]
I switched the volumemap number In DLMS and it worked to display on the website. 
Still, the first two pages are on the wrong volume. This need to be fixed.
Do eBooks need to update for these two volumes?

**Comment by xristy** [comment]
Here's an updated page 1 for volume 77:

[I1KG132500001.tiff.zip](https://github.com/buda-base/library-issues/files/3123013/I1KG132500001.tiff.zip)

and here's page 1 for vol 81:

[1KG132460001.tiff.zip](https://github.com/buda-base/library-issues/files/3123016/1KG132460001.tiff.zip)

These can be inserted in place of the current page 1's.

The eBooks could be regenerated if they're still being distributed.

**Comment by karmagongde** [comment]
eBooks are continue distributing on DLD and Lineage Drive.

**Comment by xristy** [comment]
So I suppose those two volumes should be regenerated

**Comment by TBRC-Travis** [comment]
I fixed the scan request pages.  I will regenerate the eBooks on Monday.

I'm torn whether this approach is better than what Karma initially suggested.  Given we still have to update these little do-dads and re-sync when we switch the volumeMaps it's not that much more effort to rename the files and re-sync the whole thing.

**Comment by xristy** [comment]
If we weren't using the _annoying_ two tbrc pages then there would be not so much an issue.

We could automate deleting the two tbrc pages and updating the imagegroups if we decided to jettison them. The manifest and metadata should suffice as we discussed at the retreat in February

**Comment by karmagongde** [comment]
We should not delete the scan request 2 pages from the work numbers which has an outline. Then all the outline images number will off by 2 pages.

**Comment by xristy** [comment]
It's feasible to use small scripts on tbrc.org and buda1.bdrc.io to adjust absolute outlines by -2. So it's possible to safely delete the first two pages.

**Comment by eroux** [comment]
thanks!
