### ISSUE TITLE
new topics for NGMCP database records

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#236]
The Sanskrit texts of NGMCP (in the same spreadsheet) are categorized in topics, some of them not present in BDRC:

1. the most obvious one is *Purāṇa* / *sngon gyi rabs* / *Mythologized stories*
2. there is also a more general *Kathā* / *gtam* / *story* (we have more specific topics but we need a more general one in this case)
3. this is more a question: we have the Sanskrit topic *Saṅgīta* that could correspond to either *mgur* or *glu*, if you don't have any strong feeling about it, *mgur* looks like the best match but if you have another idea don't hesitate!

**Comment by karmagongde** [comment]
I have created new topic for sngon gyi rab T2KG207410. 
For the Story T216 would be fine.
T6 mgur glu is for songs of realization and T246 glu gzhas is for general songs.

**Comment by eroux** [comment]
Thanks a lot!
