### ISSUE TITLE
wrong publication date

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#239]
https://www.tbrc.org/#!rid=W8LS20263 says the publication date is 2104, which is probably a typo for 2014

**Comment by eroux** [comment]
after running a quick query, these also have events in the future:

- [ ] W1TLMTGA003152 (2041)
- [ ] W8LS23472 (2101)
- [ ] W3CN8305 (2104)
- [ ] W8LS20263 (2104)
- [ ] W1TLMTGA002388 (2207)
- [ ] W00KG09700 (2885)
- [ ] W2PD19364 (2107)
- [ ] W1PD159529 (2107)
- [ ] W1KG9841 (17736)
- [ ] P4CZ296781 (2085)
- [ ] P1TD6 (shifted 100 years)
- [ ] P4925 (16uuuu should just be 16uu)
- [ ] P11MS235 (17uuuu should just be 17uu)
- [ ] P1AG23 (12uu12uu should just be 12uu)

**Comment by karmagongde** [comment]
Corrected all the Publication Year and Person Record Year. Except W1TLMTGA003152 and W1TLMTGA002388. These two work numbers are not of BDRC. There are from Dzongsar Library, India.

**Comment by eroux** [comment]
thanks a lot!
