### ISSUE TITLE
wrong tbrcintro image count on volumes of W29468

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#240]
The image groups of https://www.tbrc.org/xmldoc?rid=W29468 indicate

```
<ig:images intro="0" tbrcintro="0" text="0" total="626"/>
```

while in fact there are 2 intro pages. Chris can you fix it? (I think you have a query for that)

**Comment by xristy** [comment]
Done

**Comment by eroux** [comment]
thanks!
