### ISSUE TITLE
incorrect lccn data

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#241]
related to https://github.com/buda-base/library-issues/issues/238 :

Strange `sa` prefix:

- W1KG9848: `sa 64006710`
- W19802: `sa 64006710`
- W1KG6049: `sa 68019390`
- W1KG9407: `sa 68020880`
- W1KG6050: `sa 68020724`
- W1KG18239: `sa 63004115`
- W1KG17446: `sa 68019371`
- W00KG09737: `sa 68020881`
- W00KG09387: `sa 68020888`
- W1KG16744: `sa 65000840`
- W1KG23487: `sa 68020010`
- W1KG17280: `sa 68020900`
- W1KG5965: `sa 68020705`
- W2CZ8088: `sa 65000390`
- W1KG18757: `sa 68020458`
- W1KG16732: `sa 63000247`
- W1KG5735: `sa 68020195`
- W1KG15408: `sa 68020151`
- W1KG21721: `sa 68020180`
- W22106: `sa 66005123`
- W21891: `sa 68020324`

Confusion of lccn and call number

- W1PD88997: `ds793.l444 l52 1997 ft meade`
- W1KG518: `pl3705 (p-pz22)+`
- W1PD89051: `bq7670.4. .b555 2006 tib cage`
- W1KG22348: `bq7662.4.m5463 k66 1976`
- W1KG21755: `pl3633 .b75 1988`

Plainly wrong:

- W21503: `none`
- W27923: `unk 85020444`
- W11818: `82900640.`
- W21621: `[95906008]`
- W1KG3972: `75905458, 75905459`
- W12827: `75903140.`
- W30323: `74900490; unk84008490`

Legal but not existent (must be a typo somewhere)

- W24000: `83904363`
- W22150: `79903503`
- W10302: `76902699`
- W1KG23517: `83902722`
- W18580: `79905082.`
- W25111: `2004326231`

**Comment by karmagongde** [comment]
Hi, Do you want me to fix these issues manually?
Karma

**Comment by xristy** [comment]
In the _Strange sa prefix_ list it may be necessary to check each one; however, using [https://catalog.loc.gov/vwebv/search](https://catalog.loc.gov/vwebv/search) for `sa 64006710` retrieves the expected record. The LoC permalink is written w/o the space like: [https://lccn.loc.gov/sa64006710](https://lccn.loc.gov/sa64006710), and the LCCN is reported as `sa 64006710`.

In the _Plainly wrong_ list:
- W27923: `unk 85020444`

The LCCN is written as `unk85020444`. In other cases at LoC, there is a space between `unk` and the digits. Same w/ `sa` and digits.

**Comment by eroux** [comment]
indeed, the `unk` and `sa` are correct... sorry!

**Comment by karmagongde** [comment]
Hi Elie,
I am fixing the LC classification listed above. Almost done, I will let you know when it is completed.
Karma

**Comment by eroux** [comment]
thanks a lot!

**Comment by karmagongde** [comment]
Hi Elie,
I kept the listed on Strange sa prefix because LoC has same.
Rest I checked and made the correction. 
Some I did not find mistakes so kept as it is. see below:
W22150: 79903503
W1KG23517: 83902722
Best,
Karma

**Comment by eroux** [comment]
excellent, thanks!
