### ISSUE TITLE
chapters marked as texts in outline of W1PD96348

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#244]
in the outline of https://www.tbrc.org/#!rid=W1PD96348 the most detailed level of the outline seem to be chapters, but they are marked as texts. If they are chapters can you please mark them as such? That helps the MARC export

**Comment by karmagongde** [comment]
Hi Elie,
I think there are many outlines which have chosen chapters. If this work is the only then I can fix manually.  Please let me know.
Karma

**Comment by eroux** [comment]
Hi, thanks for the answer, I'm waiting for an email from Columbia about that, I'll keep you updated

**Comment by eroux** [comment]
let's close this, it's not relevant anymore
