### ISSUE TITLE
works with no images in CTC

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#246]
Hi Karma, here are 11 works that are in CTC but have no image group:

W4PD5184
W4PD5187
W4PD5190
W4PD5180
W4PD5178
W4PD5192
W4PD5191
W4PD5181
W4PD5188
W4PD5183
W4PD5182

Thank you!

**Comment by karmagongde** [comment]
Hi Elie,
These work numbers are not in CTC. Paldor mistakenly selected Production Information. Since all the work numbers are released on Sept. 2018 and CTC 5 and others are released a long time ago. 
I will remove Product Information in these 11 works.
Best,

**Comment by karmagongde** [comment]
Hi Elie,
I just removed all the Production Information (CTC) form above 11 work numbers.
Karma

**Comment by eroux** [comment]
ok thanks!
