### ISSUE TITLE
update to Esukhia outlines

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#247]
There's been a recent update to the (~200?) outlines made by Esukhia in 2013 - 2016. The new ones are on https://drive.google.com/drive/u/0/folders/0B6CXfwJdHBjAMWhJaUJVSHRSUFk (the folders with the suffix `B` are the updated ones). They should be in a format that can be processed through the [import mechanism](https://github.com/buda-base/convert-2-outline-xml/). 

The update consists mostly in spelling fixes. We should import them in eXist at some point, as the librarians will start working on fixing spelling errors and it's probably best if they don't do the same fix twice.

NT will produce a zip with all the csv files with normalized file names and add it to this issue

**Comment by xristy** [comment]
Now that the [convert-to-outline-xml](https://github.com/buda-base/convert-2-outline-xml) has been revamped perhaps NT can run it on the various csv files. Once there's a set of xml outline files it's a matter of a minute or two to upload them to eXist-db

**Comment by eroux** [comment]
sure, why not yes

**Comment by karmagongde** [comment]
I sent approximate 50 outlines numbers to NT to make correction of image numbers. Those were 2 pages off in outline image numbers and Travis sent images files of those 50 work numbers to NT to check and make correct image numbers in outlines. Proofread and fixing spelling error in these outlines is wonderful.

**Comment by eroux** [comment]
Here are the csv files:

[Esukhia-outlines.zip](https://github.com/buda-base/library-issues/files/3468750/Esukhia-outlines.zip)

The next step is to convert that into xml, I'll see if I can do that tomorrow

**Comment by xristy** [comment]
Here's the output for checking. I'll upload if it's approved:

[Esukhia-outlines-Out.zip](https://github.com/buda-base/library-issues/files/3468827/Esukhia-outlines-Out.zip)

**Comment by eroux** [comment]
Thanks a lot! 

@karmagongde , @ngawangtrinley : please check that the 2 pages offset Karma talked about is fixed in these files

**Comment by ngawangtrinley** [comment]
O1KG4191 has some issues, will fix in the morning, and look for more

**Comment by jeehuajian** [comment]
issue fixed
[esukhia-outline.zip](https://github.com/buda-base/library-issues/files/3521333/esukhia-outline.zip)

**Comment by eroux** [comment]
Thanks! A last problem with the new outlines: can you remove the first line when it's just the general work?

For instance in the outline for W1KG13693, the first line goes from image 1 to image 862 and is just the name of the work. Can you please remove the lines following this pattern? (Warning, the first two columns of the first line shouldn't be removed).

Example:

current csv is:

```csv
WORK RID,Volume,Title page title,archive start,imprint start,archive end,imprint end
W1KG13693,1,ནག་པོ་ཆེན་པོའི་ཆོས་སྐོར།,1,,862,
,,དཔལ་རྡོ་རྗེ་ནག་པོ་ཆེན་པོ་གུར་གྱི་མགོན་པོ་ཁྲོ་བཅུའི་གཏོར་བཟློག་གི་ཆོ་ག་བདུད་ལས་རྣམ་པར་རྒྱལ་བའི་མཚོན་ཆ་ཆེན་པོ།,3,1,49,24
```

it should be

```csv
WORK RID,Volume,Title page title,archive start,imprint start,archive end,imprint end
W1KG13693,1,དཔལ་རྡོ་རྗེ་ནག་པོ་ཆེན་པོ་གུར་གྱི་མགོན་པོ་ཁྲོ་བཅུའི་གཏོར་བཟློག་གི་ཆོ་ག་བདུད་ལས་རྣམ་པར་རྒྱལ་བའི་མཚོན་ཆ་ཆེན་པོ།,3,1,49,24
```

**Comment by jeehuajian** [comment]
Esukhia outline issue fixed
[esukhia outline.zip](https://github.com/buda-base/library-issues/files/3539162/esukhia.outline.zip)

**Comment by eroux** [comment]
looks good to me, thanks a lot! @xristy if these look ok to you, I think we could import them

**Comment by eroux** [comment]
@jeehuajian there were a couple of bugs in the import script, and I don't want to bother you too much in case we find more, can you please send just the csv files? We'll handle the conversion ourselves.

**Comment by jeehuajian** [comment]
Esukhia outline csv file
[esukhia-outline csv.zip](https://github.com/buda-base/library-issues/files/3549178/esukhia-outline.csv.zip)

**Comment by eroux** [comment]
Thanks!

**Comment by eroux** [comment]
@xristy can you try importing these ones?

[esukhia-outlines-xml.zip](https://github.com/buda-base/library-issues/files/3550219/esukhia-outlines-xml.zip)

**Comment by eroux** [comment]
thanks a lot! Just to be sure, did you fix them? If so I'll close the issue

**Comment by eroux** [comment]
thanks!

**Comment by ngawangtrinley** [comment]
Thanks Chris!

**Comment by jeehuajian** [comment]
@eroux @xristy Please check for esukhia outline. 25 more new outlines. (these are different from the last one) 
[Esukhia outline-csv(C).zip](https://github.com/buda-base/library-issues/files/3558562/Esukhia.outline-csv.C.zip)

**Comment by xristy** [comment]
The 25 outlines have been uploaded

**Comment by xristy** [comment]
see issues #248 and #249
