### ISSUE TITLE
problem accessing images for W28974

### ISSUE THREAD

**Issue by xristy** [buda-base/library-issues#248]
The metadata indicates that there are 420 pages but an error occurs accessing the images on tbrc.org and library.bdrc.io

**Comment by eroux** [comment]
the problem is that the images are in 

s3://archive.tbrc.org/Works/e0/W28974/images/W2874-I1KG12439/

instead of

s3://archive.tbrc.org/Works/e0/W28974/images/W28974-I1KG12439/

(the second work RID is missing a `9`)

@TBRC-JimK can you resync?

**Comment by TBRC-JimK** [comment]
Done

**Comment by eroux** [comment]
Thanks! The `dimensions.json` is not fully generated though, it just contains the filenames and is missing the dimension information

**Comment by TBRC-JimK** [comment]
Ok, I'll re-run the dimensions builder.

**Comment by TBRC-JimK** [comment]
Done.

**Comment by eroux** [comment]
thanks!
