### ISSUE TITLE
new W IDs for rKTs works

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#253]
Hi @karmagongde , can you please create some W RIDs for the following resources?

- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=bardan Zanskar 8 volumes
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=charang Lahaul
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=chemre Ladakh ? volumes
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=egoo Ladakh 1 volume
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=hundar Nubra
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=matho Ladakh
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=neruk Zanskar
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=phugthar Zanskar 9 volumes
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=reruk Zanskar
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=skyurbuchan Ladakh 11 volumes
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=stongde Zanskar
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=stagrimo Zanskar
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=zangla Zanskar ~100 volumes
- [ ] https://www.istb.univie.ac.at/kanjur/rktsneu/collections/affiche.php?id=tabo Spiti ~400 volumes

this will ease the collaboration with rKTs and Bruno will be able to send us some images more easily. Thanks!

**Comment by karmagongde** [comment]
Hi Elie,
Are these images are the same as the images gave us by Bruno a long time ago (2013-14?)? 
If so, we already catalog them according to the contents in 2015. I found there are 97 Work numbers for the images from the "University of Vienna". To double-check could Bruno able to send me full images of one of the lists and any outlines created by rKTs. Thank you, 
W3CN1094
W3CN1302
W3CN1314
W3CN1317
W3CN1328
W3CN1332
W3CN1335
W3CN892
W3CN895
W3CN965
W3CN981
W3JT13714
W3JT13715
W3JT13716
W3JT13717
W3JT13718
W3JT13719
W3JT13720
W3JT13721
W3JT13722
W3JT13723
W3JT13724
W3JT13747
W3JT13748
W3JT13749
W3JT13750
W3JT13751
W3JT13752
W3JT13753
W3JT13768
W3JT13769
W3JT13770
W4CZ45303
W4CZ45306
W4CZ45308
W4CZ45309
W4CZ45310
W4CZ45312
W4CZ45313
W4CZ45314
W4CZ45315
W4CZ45437
W8LS15931
W8LS15932
W8LS15939
W8LS15942
W8LS15945
W8LS15946
W8LS15951
W8LS15954
W8LS15957
W8LS15960
W8LS15963
W8LS15966
W8LS15969
W8LS15972
W8LS15975
W8LS15976
W8LS15981
W8LS15984
W8LS15987
W8LS15990
W8LS15993
W8LS15996
W8LS15999
W8LS16002
W8LS16005
W8LS16008
W8LS16011
W8LS16014
W8LS16017
W8LS16020
W8LS16026
W8LS16031
W8LS16035
W8LS16039
W8LS16042
W8LS16048
W8LS16055
W8LS16058
W8LS16061
W8LS16064
W8LS16067
W8LS16070
W8LS16073
W8LS16076
W8LS16079
W8LS16082
W8LS16085
W8LS16088
W8LS16091
W8LS16094
W8LS16097
W8LS16100
W8LS16103
W8LS16106
W8LS16107

**Comment by eroux** [comment]
Thanks a lot! @brunogml there's really a lot of these that should make it to the collections spreadsheet but you know best what's what... can you take a look?

**Comment by brunogml** [comment]
It seems that all W8LS.... belongs to the same collection in Zangla. Should be one RID
For the rest, I will check in the coming days

**Comment by brunogml** [comment]
In the near future, I will crop all the rKTs pictures. The next you will get is Hemis I He. Please let the collections in the order I give it to you, because it represents the way it is preserved in the monasteries or palaces. Thanks

**Comment by karmagongde** [comment]
Hi Bruno, The new cropped images from rKTs, I will make sure Librarians will catalog as your suggestion. Please share whole images when it is ready for cataloging and to know the number of volumes is important for us to generate image group numbers. Best, Karma

**Comment by eroux** [comment]
closing, communication is using other channels
