### ISSUE TITLE
duplicate places (from SRC)

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#254]
Hi @karmagongde , [Sakya Research Center (SRC)](https://sakyaresearch.org) has a lot of place records, most of them have some BDRC IDs, and sometimes there are two, because of probable duplicates, can you please check:

- [x] https://sakyaresearch.org/places/76: G3518, G3159
- [x] https://sakyaresearch.org/places/77: G4605, G3319
- [x] https://sakyaresearch.org/places/81: G4606, G2441
- [x] https://sakyaresearch.org/places/236: G4CZ1550, G3519
- [x] https://sakyaresearch.org/places/391: G4215, G3474
- [x] https://sakyaresearch.org/places/794: G1379, G2000
- [x] https://sakyaresearch.org/places/721: G1390,G3CN55
- [x] https://sakyaresearch.org/places/813: G3170,G3CN403
- [x] https://sakyaresearch.org/places/844: G3CN52,G3CN117

? thanks!

**Comment by eroux** [comment]
I also noticed this duplicate yesterday: G3CN410 / G3168

**Comment by chungdak** [comment]
moved info from dup record "G3168"
withdrawn in favor of G3CN410
from Chungdak
_________________________________________________________
Chungdak  Nangpa | Senior Librarian
ནང་བསྟན་དཔེ་ཚོགས་ལྟེ་གནས། | Buddhist Digital Resource Center | 佛教数字资源中心
1430 Massachusetts Ave., 5th Floor Cambridge, MA 02138 | tbrc.org

**Comment by eroux** [comment]
Thanks a lot!

**Comment by karmagongde** [comment]
Hi Elie,
All the listed duplicate places are reviewed and made the necessary modification or withdrawn in case of duplicate. I requested Chungdak la to reviewed since he is an expert and has on hand knowledge of the geography of Tibet. Thank you Chungdak la.
Best,
Karma

**Comment by eroux** [comment]
thanks! Just as a note, here are the couples that have been identified as non duplicates:
- G4CZ1550, G3519
- G1379, G2000
- G1390,G3CN55
- G3170,G3CN403
- G3CN52,G3CN117

@dustcats
