### ISSUE TITLE
duplicate persons (from SRC)

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#255]
here's the same list for duplicate persons:

- [x] https://sakyaresearch.org/persons/413: P5301,P0RK537
- [x] https://sakyaresearch.org/persons/588: P0RK1103 duplicate of P3205 or P4570?
- [x] https://sakyaresearch.org/persons/602: P2922,P4068
- [x] https://sakyaresearch.org/persons/1576: P1840,P4872
- [x] https://sakyaresearch.org/persons/1925: P475,P6188
- [x] https://sakyaresearch.org/persons/208: P4544, P5302
- [x] https://sakyaresearch.org/persons/286: P869, P8LS12743
- [x] https://sakyaresearch.org/persons/351: P0RK1734, P1575
- [x] https://sakyaresearch.org/persons/731: P0RK1609, P0RK1132
- [x] https://sakyaresearch.org/persons/952: P10172, P10173
- [x] https://sakyaresearch.org/persons/963: P3058 duplicate of P5838 or P3049?
- [x] https://sakyaresearch.org/persons/1160: P7753, P4CZ15156
- [x] https://sakyaresearch.org/persons/1266: P1007, P5280
- [x] https://sakyaresearch.org/persons/1273: P0RK1080, P5471
- [x] https://sakyaresearch.org/persons/1276: P3230, P0RK819
- [x] https://sakyaresearch.org/persons/1351: P0RK1283, P00KG02781

Thanks!

**Comment by eroux** [comment]
I double checked the spreadsheet and there are pairs which are marked as duplicates in the spreadsheet but where no record has been withdrawn:
- [ ] P0RK36 = P4CZ10568
- [ ] P00EGS1016642, P0RK153
- [ ] P0RK200 = P8181

also the following have no indication, I don't know if they've been looked at?
- [ ] P0RK512 = P1880

**Comment by eroux** [comment]
Here are some answers from the SRC project regarding some pairs that have been marked as non-duplicates in the last spreadsheet:

> The RIDs P2460, P2009 certainly refer to one person that is gNyag (or sNyag) phu ba bSod nams bzang po aka [m]Tshal min pa bSod nams bzang po. See his name variants under https://sakyaresearch.org/persons/101
> 
> For clarification you can also check the biographical sources on him, such as his rnam thar under W1PD153537(outline id: O1PD1535374CZ94658) or W10247(pp. 190-193). I noticed that the Treasury of Lives also holds two separate entries of him.
> 
> I would also argue that both RIDs P10628 and P1062 refer to the Sakya master Zhang dkon mchog dpal, a disciple of 'Phags pa who prominently features in the Lamdre guru lineage.
> 
> regarding P5838 and P3049, I think that both entries refer to the Gongkar lama Tshe dbang kun mkhyen, who was the nephew of the Khyenri founder mKhyen brtse chen mo. See also the SRC entry https://sakyaresearch.org/persons/963 on him.
> The 5th Dalai Lama provides the respective information in a gloss in his record of teachings received; cf. W30183(vol. 01|ka, fol. 15b2-3): 'jam dbyangs mkhyen pa'i rtse mo {mkhyen brtse chen mo'i dpon po yin tshe dbang kun mkhyen yang zer/}
> RID P3049 seems to have taken the primary name "'jam dbyangs mkhyen brtse'i rtse mo" from here, however this refers to his uncle mKhyen rtse chen mo!
> 
> P2615 and P0RK120 are obviously duplicates for sNgags 'chang gzungs kyi dpal, but I see no relation to P10100 (rNam rgyal mgon po).
> 
> RID P9956, indeed, seems to be another duplicate of P0RK431 ('Jam dbyangs skya bo Nam mkha' dpal).

maybe it would be worth reconsidering these?

**Comment by karmagongde** [comment]
Hi Elie,
All the listed Duplicate person records are reviewed and made all the necessary modifications and withdrawn in cased of duplicate. I requested Lobsang la for this work and the work is done. Thank you Lobsang la.
Best,
Karma

**Comment by eroux** [comment]
Again as a note, the non-duplicates are:
- P0RK1103 duplicate of P3205 or P4570?
- P1840,P4872

@dustcats FYI, here's a list of new withdrawn -> replacements related to your data:
- G3159,G3518
- G3319,G4605
- G2441,G4606
- G4215,G3474
- P0RK36,P4CZ10568
- P0RK153,P00EGS1016642
- P0RK200,P8181
- P0RK512,P1880
- P5301,P0RK537
- P4068,P2922
- P6188,P475
- P4544,P5302
- P8LS12743,P869
- P0RK1734,P1575
- P0RK1132,P0RK1609
- P10173,P10172
- P3058,P5838
- P3049,P5838
- P4CZ15156,P7753
- P1007,P5280
- P0RK1080,P5471
- P0RK819,P3230
- P00KG02781,P0RK1283
- P0RK120,P2615
- P9956,P0RK431
- P2009,P2460

If you want to make a case for the non-duplicates you can do it in this issue!

**Comment by dustcats** [comment]
Meanwhile, I traced some other duplicates and a seemingly wrong teacher-student relation. Please check:

- two RIDs exist for རས་ཆེན་དཔལ་འབྱོར་བཟང་པོ།  P7009, P10257
- two RIDs exist for ཀུན་བཟང་རྩེ་པ་བསོད་ནམས་རྒྱལ་མཚན། P10261, P8775
- two RIDs exist for བསོད་ནམས་ཡེ་ཤེས་བཟང་པོ། P2GS1013, P2GS1031
- RID P3050: ཀུན་བཟང་རྩེ་པ་དབང་ཕྱུག་རྒྱལ་མཚན། This lama from Gongkar Choede was probably not the teacher of the 3rd Dalai Lama bSod nams rgya mtsho, as is indicated here. ཀུན་བཟང་རྩེ་པ་དབང་ཕྱུག་རྒྱལ་མཚན། is probably mistaken for the 3rd DL's uncle སྐུ་ཞང་ཀུན་བཟང་རྩེ་པ། aka ཀུན་བཟང་རྩེ་པ་ཆོས་ཀྱི་དབང་ཕྱུག see https://sakyaresearch.org/persons/2213 for references

**Comment by eroux** [comment]
ah thanks a lot! reopening the issue

**Comment by karmagongde** [comment]
P10257 is already withdrawn and I just have withdrawn P10261.
For P2GS1013 and P2GS1031 both have different titles ཀུན་སྤངས་ཆེན་པོ་བསོད་ནམས་ཡེ་ཤེས་དཔལ་བཟང་པོ།
and མཐོ་བཙུན་བསོད་ནམས་ཡེ་ཤེས་དཔལ་བཟང་པོ། If there is any document which shows both are the same person than I will make the correction. 
I removed the P3050 teacher-student relationship with the 3rd Dalai Lama P999. 
Thank you.

**Comment by eroux** [comment]
@karmagongde can you also take a look at some duplicates that were recently spotted:
- [ ] P0RK270,P4CZ15179
- [ ] P0RK364,P4CZ15180,P4CZ15250 (for these I'm not sure, it seems P4CZ15180 and P4CZ15250 refer to two different persons... but is there a source that explains who is who? in any case, P4CZ15180 and P0RK364 are clearly duplicates)

@dustcats I don't know if you saw Karma's question? quoting:
> For P2GS1013 and P2GS1031 both have different titles ཀུན་སྤངས་ཆེན་པོ་བསོད་ནམས་ཡེ་ཤེས་དཔལ་བཟང་པོ།
and མཐོ་བཙུན་བསོད་ནམས་ཡེ་ཤེས་དཔལ་བཟང་པོ། If there is any document which shows both are the same person than I will make the correction.

**Comment by dustcats** [comment]
@karmagongde 
This is [bZhi 'dzom Rin chen don yod](https://sakyaresearch.org/persons/157) of the Yar rgyab ruling family, a close disciple of the Fourth Shamarpa. His ordination name was bSod nams ye shes dpal bzang po. I checked several Tibetan sources and summarized my findings in [Putting Yar rgyab on the map](https://sakyaresearch.org/sources/1888), pp. 82f. n.

**Comment by eroux** [comment]
Thanks! The PDF of the article can be found here: https://epub.oeaw.ac.at/0xc1aa5576_0x0038c0ea.pdf

**Comment by karmagongde** [comment]
Thanks for the documentation. The BDRC Author record P2GS1013 is withdrawn in favor of P2GS1031. I added titles and a teacher to P2GS1031.

**Comment by eroux** [comment]
Thanks @karmagongde ! Can you also take a look at P0RK270 / P4CZ15179 and P0RK364 / P4CZ15180?

**Comment by karmagongde** [comment]
@eroux Working on these P# records in between of other works. When it is done, I will inform you.

**Comment by eroux** [comment]
Thanks a lot!

**Comment by karmagongde** [comment]
@eroux After moving all the associates work number, outline, lineage transmission, now I Withdrawn P0RK270 in favor of P4CZ15179;
Withdrawn P0RK364 and P4CZ15250 in favor of P4CZ15180.

**Comment by eroux** [comment]
thanks!
