### ISSUE TITLE
person data augmentation (from NGMCP)

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#256]
Hi @karmagongde , I've compared our data to NGMCP person data, and here are a few things that we could add:

First these dates are indicated in NGMCP but not in our data:

[dates-results.zip](https://github.com/buda-base/library-issues/files/3882510/dates-results.zip)

Then these Sanskrit names are in NGMCP but not in our data:

[names-results-skt.txt](https://github.com/buda-base/library-issues/files/3882511/names-results-skt.txt)

and finally these Tibetan names are in NGMCP but not in our data. I think some should be ignored but I let you check that on a case by case basis:

[names-results-tib.txt](https://github.com/buda-base/library-issues/files/3882512/names-results-tib.txt)

Thanks!

**Comment by karmagongde** [comment]
Hi @eroux , The date-results is helpful. I will add to our data. The names of both the Tibetan and Sanskrit, BDRC already have P# record. I will check and make modifications if necessary.
For instance, P2596: khri byang 03 = ཁྲི་བྱང ༠༣ བློ་བཟང་ཡེ་ཤེས་བསྟན་འཛིན་རྒྱ་མཚོ། 
P7878: Jayasena = Please see the attached screenshot. We already have jayasena.
<img width="846" alt="Screen Shot 2019-11-23 at 9 25 19 AM" src="https://user-images.githubusercontent.com/19337852/69480283-33b5c600-0dd4-11ea-9d62-a69dd14c68cd.png">

I am traveling to India from November 25 to Dec 21. The Librarians have been assigned lots of texts to catalog. I will online depend on network speed and workloads. I will try to solve any urgent issues need to take care of. The rest of the issues I will look after returning back.

**Comment by eroux** [comment]
Thanks a lot! This is not a pressing issue, it's just to deal with when time is right. There's no new P records to add, just some names in some cases. The data comes from an automatic query and sometimes the results are not relevant yes. If they're not let's ignore them, as you say.

I think the two issues about SRC are higher priority than this one, they're also shorter I think.

Safe travels!

**Comment by eroux** [comment]
Hi @karmagongde , I'm thinking perhaps it would be a good time to look into this? Best

**Comment by karmagongde** [comment]
Hi Elie,
Thank you for this reminder. Although I am working on NLM and other contributed images this is interesting and it will improve our data information. I will look and add anything missing in the BDRC database. 
Best,
Karma

**Comment by eroux** [comment]
ok thanks! I sorted the information of NGMPP so that only those that we don't have at all in the database are in the files of this github issue, at least that's the theory!

**Comment by karmagongde** [comment]
Hi Elie,
I reviewed the dates, and Sanskirt and add as well as modified accordingly. some of the dates, I kept the BDRC record because it has source references. 
The names-results-tib, I looked a few of them and all exist in the BDRC database.

**Comment by eroux** [comment]
Hi Karma, perfect, thanks!
