### ISSUE TITLE
third and last images not displaying for W1KG4292 and W1KG4223 etc

### ISSUE THREAD

**Issue by xristy** [buda-base/library-issues#257]
Attempting to view the third image and last image of the mentioned works on tbrc.org gives an error indicating apparently missing images. The images do appear in library.bdrc.io as poor b&w. Other works in the series such as W1KG4225 and W1KG4289 have clean color cover images.

**Comment by TBRC-Travis** [comment]
The pages failing to load were Fax4 tifs in some sort of funky state.  A simple mogrify on these would be enough to get them to load, but since they originated from nice color images I restored them back to color JPGs rather than tif files.  All set!

**Comment by xristy** [comment]
Most excewllent! Thanks
