### ISSUE TITLE
duplicate sources (from SRC)

### ISSUE THREAD

**Issue by dustcats** [buda-base/library-issues#258]
FYI: W3CN485 (https://sakyaresearch.org/sources/768) seems to be identical with the entries W2DB4567, W2DB4568, W2DB4569, W2DB4570, W2DB4571, W2DB4573

Best wishes,
Mathias

**Comment by karmagongde** [comment]
The title could be the same but publishers are different in this case. So it is a different edition. There are a few duplicates texts which we are aware of it.  The images are already paid and we have to keep both for account reason.
Best,
Karma

**Comment by eroux** [comment]
closing as different editions should indeed have different W RIDs (the bibliographical model is revised in the new platform, but we can see that in the future)
