### ISSUE TITLE
wrong page number for Derge Kangyur W22084

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#259]
in volume 6 (image group `0891`), tbrc.org indicates only 209 images, while the volume is much longer and the scan request page indicates 574 images. Do we have the rest of the images?

**Comment by karmagongde** [comment]
I checked in our archive and those folios are missing in volume 6 of Derge Kangyur W22084. Does rKTs has the complete images of volume no. 6? Please let me know. Otherwise, I have to find from other sources to make this volume complete.

**Comment by eroux** [comment]
Hi Karma, rKTs has no reason to have scans of this edition, I'm not sure who to ask... maybe @ngawangtrinley  would know?

**Comment by karmagongde** [comment]
Hi Elie, rKTs is doing research on all the Kangyur editions and I thought they might have scan images of Derge Parphud edition. Anyway, I will find the missing pages.

**Comment by brunogml** [comment]
We do not have images of the Derge Kanjur of our own. Sorry!

**Comment by karmagongde** [comment]
I got the 'dul ba cha from Gordon as well as in borders folder. I will ask Travis to sync.

**Comment by eroux** [comment]
ah excellent, thanks! Is it the same Delhi edition?

**Comment by karmagongde** [comment]
Yes, it is the same edition of Delhi.

**Comment by eroux** [comment]
Great! Maybe if we have all the volumes of this new set of scans (which is probably better than the one we currently have?) we could create a new W record and have them all online? Or is it images from the same set of scans?

**Comment by karmagongde** [comment]
I have only the volume 6 to replace.

**Comment by karmagongde** [comment]
The complete images of W22084, vol. 6 is uploaded on the website.

**Comment by ngawangtrinley** [comment]
Thanks @karmagongde, and sorry @eroux I couldn't help with that

**Comment by eroux** [comment]
thanks, excellent!
