### ISSUE TITLE
Downloaded PDF has images which are too wide to view

### ISSUE THREAD

**Issue by TBRC-JimK** [buda-base/library-issues#260]
A professor in France just wrote to me about https://www.tbrc.org/#!rid=W00KG04005. The images display fine online but the downloads are enormous (dimension-wise, not megabyte-wise).

**Comment by TBRC-JimK** [comment]
I generated a PDF from this work.  On Chrome on Windows, the PDF as seen in the browser seemed fine, but when I went to zoom in or out, the image just swelled up to an unusable zoom level, and would not shrink.

When I downloaded the PDF file and opened it in Acrobat reader DC, it warned me that images extended beyond the viewable margin, and only the left-hand third (or fourth) of each image was available

**Comment by TBRC-JimK** [comment]
W00KG04004 and W1FPL2251 do not have this behavior.
XnViewMP shows that 
[W00KG04005.props.txt](https://github.com/buda-base/library-issues/files/4010772/W00KG04005.props.txt) shows a DPI of 3x3 (with a resulting image size of 862 ")
while 
[W40KG04004.props.txt](https://github.com/buda-base/library-issues/files/4010773/W40KG04004.props.txt)
is more to scale.

**Comment by TBRC-JimK** [comment]
The W00KG04005 images on both S3 and RS3 have the same DPI (3x3).

**Comment by TBRC-Travis** [comment]
Fixed DPI and image width of images.
