### ISSUE TITLE
Fails audit tool

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/library-issues#261]
Summary 
- [x] W00KG03818
- [x] W00KG03984
- [x] W00KG04002
- [ ] W00KG0545
- [x] W00KG03568

**Comment by TBRC-JimK** [comment]
Removed bad tif 
```
jimk@Tseng:~$ cd mnt/Archive/W00KG03568/images/W00KG03568-I00KG03571/
jimk@Tseng:W00KG03568-I00KG03571$ ls -l *[ab]*
-rwx------ 1 jimk staff 670 Jul 14  2010 I00KG035710206a.tif
-rwx------ 1 jimk staff 656 Jul 14  2010 I00KG035710206b.tif
```

**Comment by TBRC-JimK** [comment]
W00KG03818, I declared errors 110, 111 as warnings.

**Comment by TBRC-JimK** [comment]
- [ ] W00KG03818
- [ ] W00KG03984
- [ ] W00KG04002
- [ ] W00KG0545

**Comment by TBRC-JimK** [comment]
Asking @karmagongde to look into W00KG0545, which has two missing images.
[FAIL-W00KG0545-2020-06-12.10.48.csv.log](https://github.com/buda-base/library-issues/files/4771706/FAIL-W00KG0545-2020-06-12.10.48.csv.log)

**Comment by karmagongde** [comment]
I checked the contents of images as well as folio numbers of W00KG0545. There are no missing contents/pages. Only the page number jumped (see after I1KG206980454 - )

**Comment by jimk-bdrc** [comment]
Verified that the penciled in page numbers on each image in W00KG0545 had no gaps in sequence, and fixed the sequence so that audit tool would pass it. Checked on legacy and BUDA.
