### ISSUE TITLE
duplicate / misplaced image groups

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#263]
- [ ] [I1FEMC01](https://www.tbrc.org/#!rid=I1FEMC01) is referrenced in both [W1FEMC01](https://www.tbrc.org/#!rid=W1FEMC01) and [W1FEMC02](https://www.tbrc.org/#!rid=W1FEMC02) (indicates W1FEMC01)
- [ ] [I3CN624](https://www.tbrc.org/#!rid=I3CN624) is referrenced in both [W3CN616](https://www.tbrc.org/#!rid=W3CN616) and [W3CN472](https://www.tbrc.org/#!rid=W3CN472) (indicates W3CN472)
- [ ] [I3CN629](https://www.tbrc.org/#!rid=I3CN629) is referrenced in both [W3CN419](https://www.tbrc.org/#!rid=W3CN419) and [W3CN626](https://www.tbrc.org/#!rid=W3CN626) (indicates W3CN419)

@xristy there's one you created here I think, for the two others, @karmagongde can you take a look?

**Comment by xristy** [comment]
@karmagongde appears to have repaired these

**Comment by eroux** [comment]
I'm not sure what makes you say that? I still see `I3CN624` in both
- https://www.tbrc.org/xmldoc?rid=W3CN472
- https://www.tbrc.org/xmldoc?rid=W3CN616

**Comment by karmagongde** [comment]
I have repaired W1FEMC02. I am on the other 2 work numbers. It seems to machine error. Anyway, I will change the IG number of W3CN472 and W3CN419. @TBRC-Travis Please replace these two work numbers.

**Comment by eroux** [comment]
ok thanks!

**Comment by TBRC-Travis** [comment]
@karmagongde I've fixed W3CN472 and re-synced the images.

Images are not yet available for W1FEMC02 or W3CN419 so those don't require fixing.

**Comment by karmagongde** [comment]
Both the W3CN472 and W3CN419 has a new IG number. Thank you for re-synced the images of W3CN472. @TBRC-Travis 
No required to fix W3CN419 & W1FEMC02.
W1FEMC02 is from Phnom Phen, Cambodia.

**Comment by eroux** [comment]
excellent, thanks!
