### ISSUE TITLE
possible scan issue in W1FEMC031274

### ISSUE THREAD

**Issue by xristy** [buda-base/library-issues#266]
@TBRC-JimK There's a possible scan issue on at least page 22 of W1FEMC031274 where the top left line is cut off:

![Screen Shot 2020-02-14 at 10 28 22 AM](https://user-images.githubusercontent.com/3542294/74549371-23197580-4f15-11ea-86d2-f9c360fb9088.png)

This bring to the fore the idea of recording "best available image" as has been done for some older TBRC images so that users know that the image represents the accurate digitization of the material available.

**Comment by TBRC-JimK** [comment]
This was a cropping error going from raw to sources, so it's not the best available. I'll let DDD know.

**Comment by TBRC-JimK** [comment]
Actually, it only appeared to be a crop form raw to sources, because the raw files were upside down. I asked DDD to resubmit this work

**Comment by TBRC-JimK** [comment]
No further work needed on this issue. The images are what they are.
