### ISSUE TITLE
Image quality in W1KG18437

### ISSUE THREAD

**Issue by TBRC-JimK** [buda-base/library-issues#267]
Matthew Kapstein, professor of Tibetan in Paris, wrote to me to ask if anything can be done about the images for W1KG18437. The books have hundreds of full color photos but the web images aren’t very good. I’m hoping it’s just a matter of over compression and that we can reprocess them and offer him and others a much better version of this work.

**Comment by TBRC-JimK** [comment]
Hi Travis, I just assigned this to you so you can close

**Comment by TBRC-Travis** [comment]
Just so it's documented here, we ended up re-scanning this work through the generosity of IA's digitization lab at the Boston Public library.  The original publication contains pecha images that are of mediocre quality but we were able to produce higher quality images from the original books.  So the end result is as good as it can get.
