### ISSUE TITLE
missing even pages in volume 8 of W1KG12075

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#271]
Hi @karmagongde it seems all the even pages of volume 8 of W1KG12075 are not scanned, starting with page numbered 274 in the original (image number 284 in our viewer). Do we have them in our archives? Thanks!

**Comment by karmagongde** [comment]
Hi Elie,
I checked in Archive and there are no images for the missing pages of W1KG12075, volume no. 8. We do not have physical text in the office and a scanner person. I will check with other organizations like CIHTS and try to get the missing pages later.

**Comment by eroux** [comment]
ok thanks! Can you put a short note in the record about it?
