### ISSUE TITLE
tbrcintropages wrong values

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#272]
The following have a wrong value for tbrcintropages (0, should be 2):
- W1660
- W7500
- W23703
- W10200
- W20325
- W25185
- W20479
- W21939
- W29193
- W23923
- W19617
- W20510
- W26672
- W1PD83960
- W30532
- W26071
- W22703
- W3CN22341

- W21729
- W23948
- W6486
- W25095
- W26010
- W27478
- W6486
- W20325

**Comment by eroux** [comment]
[imgls.zip](https://github.com/buda-base/library-issues/files/4837089/imgls.zip)

here's a bigger list

**Comment by xristy** [comment]
The tbrcintro has been updated to 2 for the 2141 imagegroups of the 774 works in the list

**Comment by eroux** [comment]
excellent, thanks!
