### ISSUE TITLE
missing images for old work records

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#273]
Hi @karmagongde I got a request for these: W3CN883 and W3CN1356. They're both relatively old (2014/2015) but I can't find the images anywhere in the backlog... is this something we might have somewhere? If not, we maybe should withdraw them... Best

**Comment by karmagongde** [comment]
Hi @eroux 
I am 100% sure the images for these work numbers are in the backlog. I wonder why you did not find them in the backlogs. Some of the TBRCRS needs admin permission and I am not sure I have permission. Travis knows very well of these backlogs and he handles and processes them. 

Regarding the catalog records in the BDRC database, there are few statuses.
1. Work records with the images online are well and excellent.
2. Old and new work records without the images online yet the images are still on backlogs. 
3. Work records created for the bibliographic record purpose so the BDRC users will know such text is available in other places. For instance texts in Potala Palace. Such catalog records shall stay on the BDRC database for bibliographic records and maybe get images in the future. 
4. If there are two identical catalog records and one is without the images then librarians will withdraw the records without images.

Best

**Comment by eroux** [comment]
ok thanks! @TBRC-Travis do you know where these might be on RS5?

**Comment by TBRC-Travis** [comment]
@eroux these are in our backlog here -- RS5:Incoming/scans/ReadyToProcess/Other

If I can prioritize these in my processing queue if you like.  I'll be sending more works out tonight.

**Comment by eroux** [comment]
Excellent, thanks! If you are in a state of equanimity towards the backlog then yes please for the prioritization! If it disturbs your workflow don't, I'll find a way to pass these on

**Comment by TBRC-Travis** [comment]
No problem at all.  I'll have them published this evening.

**Comment by eroux** [comment]
Thanks a lot!

**Comment by TBRC-Travis** [comment]
These have now been published on tbrc.org:

https://www.tbrc.org/#!rid=W3CN1356
https://www.tbrc.org/#!rid=W3CN883

Their bdrc.io equivalents will likely be available once post-processing completes within the next hour or so.

**Comment by eroux** [comment]
thanks a lot, appreciated!
