### ISSUE TITLE
first page missing in W1KG12766

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#274]
Hi all, I'm not sure who I should assign the issue to but the second page of W1KG12766 is missing from our images while it's in the source PDF (I sent it a year ago). Here it is:

http://eroux.fr/1v.jpg

**Comment by eroux** [comment]
@karmagongde what do you think?

**Comment by karmagongde** [comment]
Hi @eroux 
Since we have the missing page in the web image is available in the source PDF. It is easy to add and sync by Travis. I will ask him to take care of it.  When it is done, I will let you know.

**Comment by eroux** [comment]
thanks!

**Comment by TBRC-Travis** [comment]
@eroux @karmagongde can you point me at the source PDF?  I don't see it in the "sources" directory in the archive.

**Comment by karmagongde** [comment]
Hi @TBRC-Travis, here is the source PDF link from Elie.
http://eroux.fr/khrulsel.pdf

**Comment by TBRC-Travis** [comment]
thanks!

**Comment by TBRC-Travis** [comment]
Fixed.

**Comment by eroux** [comment]
thanks!
