### ISSUE TITLE
W3PD887 restriction

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#277]
Hi Karma, W3PD887 is markes as *temporarilyRestricted*. It's been 4 years now, I'm thinking perhaps this could be made open access? Thanks!

**Comment by karmagongde** [comment]
Hi Elie,
Sure, I just released W3PD887.
Some of the USAID texts marked Temporarily Restricted are for the safety of the person who provided the texts.
Best,

**Comment by eroux** [comment]
excellent, thanks!
