### ISSUE TITLE
wrong printery on W1KG825

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#278]
(reported by a scholar) W1KG825 and W294 (i.e. 5th Dalai Lama's collected works in 25 vols.) are not Zhol prints, but seem to be from the dGa' ldan pho brang printery at 'Bras spungs
See, for instance, the colophon of the Fifth Dalai Lama's [དཔལ་ཀུན་ཏུ་བཟང་པོའི་འཆམས་ཀྱི་བརྗེད་བྱང་ལྷའི་རོལ་གར།](https://sakyaresearch.org/sources/3466) and [Three dkar chag's](https://sakyaresearch.org/sources/710) [1970], p. 184.3-5: དཔལ་ལྡན་འབྲས་སྤུངས་སུ་གསུང་སྤར་ཡོད་གྲས་ལ། དགའ་ལྡན་ཕོ་བྲང་གི་སྤར་ཁང་དུ། [...] ༧རྒྱལ་མཆོག་ལྔ་པ་ཆེན་པོའི་གསུང་འབུམ་པོད་ཉི་ཤུ་རྩ་གཅིག་ལ་གྲངས། ༧༧༥༧

**Comment by karmagongde** [comment]
Based on Three dkar chag's [1970], I changed the printery source to 'bras spungs dga' ldan pho brang gi par khang for W1KG825 and W294.

**Comment by eroux** [comment]
excellent, thanks!
