### ISSUE TITLE
Add CTC 17 to website

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/library-issues#282]
Karma has selected the works for CTC 17, see [here for details](https://github.com/buda-base/archive-ops/issues/148)

In the past we've only had to do this for tbrc.org but this of course will need to be updated on BUDA now as well

**Comment by xristy** [comment]
PR01CTC17 created and the 230 works added to it. Link from CTC page on tbrc.org added.

To Do: create a 17 thumbnail

**Comment by TBRC-Travis** [comment]
Thanks @xristy.  It's showing up as expected here:  https://www.tbrc.org/#!specials/core/ctc17

Are we planning to create a similar landing page for the new site?  

Also do you want me to create a separate ticket for the thumbnail or just leave this open.

**Comment by xristy** [comment]
It seems reasonable to have a CTC page. That's a call for @eroux. I think a separate issue is reasonable somewhere, like public-digital-library.

**Comment by TBRC-Travis** [comment]
@eroux what do you think?  should we create a separate request to add a CTC page and close out this ticket?

**Comment by eroux** [comment]
here it is: https://library.bdrc.io/search?r=bdr:PR1CTC17&t=Scan&s=title%20forced
