### ISSUE TITLE
records missing a status on tbrc.org

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#283]
The following models don't have a status at all (not released nor withdrawn or anything) and so are not discoverable on tbrc.org (they can't appear in search results) and are not migrated to BUDA. Some of them look like they should be available as they have related persons, works, etc. @karmagongde can you add please a status to them so that they're accessible? thanks!

- [x] P1KG15997
- [x] P4CZ16797
- [x] P1KG20671
- [x] P4CZ15545
- [x] P1KG20864
- [x] P4CZ16899
- [x] P2PD18941
- [x] P1KG23550
- [ ] P4CZ16781
- [x] P1KG21241
- [ ] P4CZ15460
- [ ] P4CZ16822
- [x] P4CZ300001
- [x] P1KG23412
- [x] P1KG21242
- [x] P1KG18655
- [ ] P4CZ15631
- [x] P1KG21581
- [x] P4CZ16820
- [x] P2KG765
- [x] G1TD5
- [x] G1PD110134
- [x] L10MS14672
- [x] T2CZ5183
- [x] T012AG03552
- [x] T1CZ27
- [x] T012AG03340
- [x] T00AG0326
- [x] T1CZ6
- [x] T1CZ4663
- [x] T012AG03389
- [x] T4CZ15215
- [x] T00AG01368
- [x] T2CN4390
- [x] T00AG01366
- [x] W4CZ346739

**Comment by karmagongde** [comment]
@eroux The above checked marked listed records are reviewed and changed status accordingly.
But, the following records are changed to Provisional. Kelsang will use these P# numbers later.
P4CZ16781......Provisional
P4CZ15460.....Provisional
P4CZ16822.....Provisional
P4CZ15631......Provisional
Best,

**Comment by eroux** [comment]
Thanks! It seems the operation didn't work on some records though... for instance P4CZ16899 still doesn't have a status although it's checked in the list and a new log entry has been created... but most records look ok

**Comment by karmagongde** [comment]
@eroux I assigned all the CZ to Kelsang and she missed it. Anyway, I fixed the P4CZ16899. Now it will work fine.

**Comment by eroux** [comment]
perfect, thanks!
