### ISSUE TITLE
RIDs of the Lokesh Chandra and NLM collections

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#284]
It would be good to be able to get all the RIDs of the Lokesh Chandra and NLM collections. A part can be automated I suppose (especially the `W1NLMxxx`), but a part can't be fully automated... @karmagongde how could we proceed to get the RIDs?

related to https://github.com/buda-base/public-digital-library/issues/245

**Comment by karmagongde** [comment]
@eroux Regarding RIDs of the Dr. Lokesh Chandra, there are two things, 1. The scanned texts of his collection by Mangaram and 2. Published by international academy of Indian culture, [sata-pitaka series]. For the second one has its own Series Name and Number, Publisher name, location, and date. Are we going to treat them as separate or the same group? 
I will try to get full RIDs. In case missed some and found later, we should have an easy way to add it manually.

**Comment by eroux** [comment]
hmmm good question... I would think only number 1 could be good in a collection... @JannTibetan what do you think?
