### ISSUE TITLE
Recently synced rKTs collections

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#286]
Looking at the recent syncs, I noticed a few things coming from rKTs so I asked @brunogml what they were, it turns out they are 5 volumes kept in Tsharang (in Kinnaur, so not the same as Tsharang in Mustang) that the team in Vienna took pictures of in 2012. The corresponding RIDs are:
- W3JT13714
- W3JT13716

But there are many others in the same RID range, such as:
- W3JT13715
- W3JT13717
- W3JT13718
- W3JT13719
- W3JT13720
- W3JT13721
- W3JT13722
- W3JT13723
- W3JT13724

@brunogml can you indicate what these are?

**Comment by eroux** [comment]
Note that W1PD127348 and W1PD127771 are also from Vienna but have the provenance information (monastery, etc.) in a note. I'm starting to think that a collection for the Viennese scans (`Cultural History of the Western Himalaya-Project, "Tibetan Manuscripts" (University of Vienna)`) would be relevant... what do you think @xristy ? There would be all the RIDs that we cited plus:
- W3CN1317
- W1PD127393
- W1PD128753
- W1KG13607
- W2KG209840
- W2KG210298
- W4CZ45315
- W3CN1302

plus probably more but I can't find them... it's a bit strange because all these don't turn up in a search for "University of Vienna", while they have it in the bibliographic note... maybe the search doesn't search this field? If not, is there a way to trigger a search on that by hand? @brunogml , @karmagongde if you see more RIDs in this collection let's list them in this issue

**Comment by brunogml** [comment]
W3JT13714  to W3JT13718 (W3JT13718 has no images) are from a Nunnery in Tsharang (Kinnaur) 
https://www.google.at/maps/@31.4272402,78.5817694,1131m/data=!3m1!1e3
The nunnery hosts a large collection of mss, but we get permission to photograph only 5 volumes. 
W3JT13719 is from Lari (Kinnaur).
For the rest, I have to check further (W3JT13723 and W3JT137124 have no images)

**Comment by eroux** [comment]
Thanks! @karmagongde can you add this info to the records? Also, where are the images of W3JT13723 and W3JT137124? I can't find them on RS5... I'll send Bruno a few images so that he can see what they are

**Comment by karmagongde** [comment]
All the W3JT has a source note in the catalog record.

![Screen Shot 2020-09-09 at 1 52 11 PM](https://user-images.githubusercontent.com/19337852/92635600-1a6b0100-f2a4-11ea-98f8-36951f0a49af.png)

**Comment by eroux** [comment]
ooooh thanks, I skipped that! wow, so many different ways to encode the data...

Unrelated: @xristy could you rename the collection to "University of Vienna - Tibetan Manuscript Project Vienna (TMPV)"?

**Comment by xristy** [comment]
The unrelated change has been made

**Comment by eroux** [comment]
Ok yes perfect! I think just the name "Namgyal" is a very insufficient description for a place, it's not the most uncommon name of the Tibetan language... for the record it's this Namgyal: https://goo.gl/maps/jzJY63voP6QrS7Ma7 (31.8106387,78.65239)
