### ISSUE TITLE
"editing" records with synced images

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#289]
Hi @karmagongde this may be normal but just checking. These 7 records:
- W2KG207574
- W2PD17417
- W4CZ307784
- W1KG15909
- W2KG209271
- W1KG15911
- W2KG207346

are in status "editing" but have synced images. Perhaps some of them could be released?

**Comment by eroux** [comment]
Note also these synchronized works in other non-released status. I guess those are plainly wrong? If you want all these switched to "released" we can make a query.

status seeking out:

- W1KG14364
- W1KG14346

status accessionned:

- W4CZ74086
- W4CZ74318
- W4CZ74318
- W4CZ74318
- W4CZ74217
- W4CZ74421
- W4CZ74421
- W4CZ74421
- W4CZ74100
- W4CZ74193
- W3CN6618
- W3CN6618
- W4CZ74412
- W4CZ74089
- W4CZ74180
- W3CN3030
- W3CN3031
- W3CN3031
- W3CN3031
- W3CN3031
- W3CN3031
- W3CN3031
- W3CN3031
- W3CN3031
- W3CN3031
- W3CN3031
- W4CZ74196
- W4CZ74190
- W3CN3032
- W3CN3032
- W4CZ74325
- W4CZ74098
- W4CZ74080
- W4CZ74080
- W4CZ74080
- W4CZ74080
- W4CZ74080
- W4CZ74080
- W3CN4364
- W4CZ74320
- W4CZ74194
- W4CZ74092
- W3CN8366
- W4CZ74559
- W4CZ74429
- W4CZ74429
- W4CZ74429
- W4CZ74429
- W4CZ74321
- W4CZ74218
- W4CZ74081
- W4CZ74322
- W4CZ74323
- W4CZ74317
- W4CZ74091
- W4PD2010
- W4PD2010
- W4CZ74087
- W3CN4362
- W4CZ74101
- W4CZ74418
- W4CZ74174
- W2PD19897
- W2PD19897
- W4CZ74319
- W4CZ74319
- W4CZ74219
- W4CZ74170
- W4CZ74170
- W4CZ74102
- W4CZ74426
- W3CN3335
- W3CN3335
- W3CN3335
- W3CN3335
- W3CN3335
- W3CN3335
- W3CN3335
- W8LS19326
- W8LS18398
- W3CN4317
- W3CN4342
- W3CN4363
- W3CN3039
- W4CZ74189
- W4CZ74197
- W3CN3429
- W4CZ74088
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W4PD3593
- W3CN3406
- W3CN3406
- W3CN3406
- W3CN3406
- W3CN3034
- W3CN3034
- W4CZ74187
- W4CZ74316
- W4CZ74316
- W29989
- W1KG24278
- W4CZ74186
- W4CZ74090
- W4CZ74079
- W4CZ74378
- W4CZ74192
- W4CZ74181
- W4CZ74183
- W3CN6338
- W3CN6338
- W3CN6338
- W3CN6338
- W3CN6338
- W3CN6338
- W3CN6338
- W3CN6338
- W4CZ74484
- W4CZ74099
- W4PD2097
- W4PD2097
- W4PD2097
- W4PD2097
- W4PD2097
- W4PD2097
- W4PD2097
- W4PD2097
- W4PD2097
- W4PD2097
- W2CZ8048
- W4CZ74188
- W3CN7826
- W4CZ74487
- W4CZ74487
- W4CZ74487
- W4CZ74487
- W4CZ74487
- W4CZ74094

**Comment by eroux** [comment]
Also note that some of these are in CTC16 like W4PD3593 so I don't think people are able to access it even though they paid for it

**Comment by karmagongde** [comment]
@eroux 
I see the status "accessioned" problem. Sometime in 2017, Jan 24, unknowingly batch of work numbers were converted to "accessioned" by a script. We will fix them. (see screenshot)

![Screen Shot 2020-09-11 at 11 38 48 AM](https://user-images.githubusercontent.com/19337852/92949544-4237a180-f429-11ea-9f3e-3757ab67ef90.png)

**Comment by eroux** [comment]
Yes I saw that too, it's weird... thanks for fixing the status, that will add 200 more scans to our collection at almost no cost, that's quite good!

**Comment by eroux** [comment]
Also, these other records have been made accessioned with the same script and are still accessioned, maybe they should be released too?

- W1GS9
- W1KG1096
- W1KG16158
- W1KG16277
- W1KG16452
- W1KG17282
- W29493
- W2DB4623
- W2DB4625
- W3CN3027
- W3CN3028
- W3CN4361
- W4CZ74085
- W4CZ74093
- W4CZ74096
- W4CZ74097
- W4CZ74175
- W4CZ74175
- W4CZ74324
- W4CZ74369

**Comment by karmagongde** [comment]
@eroux Changing the status of the Above listed work numbers are done.

**Comment by eroux** [comment]
wonderful, thanks!
