### ISSUE TITLE
Adding another Bibliographic Note on NLM Work number

### ISSUE THREAD

**Issue by xristy** [buda-base/library-issues#290]
ACIP gave a list of donor/supporter names for the NLM scanning project which needs to add on the NLM work numbers. 

Could you please write a script and batch import them to the catalog records on another "Bibliographic Note Field".

The same work will repeat in the future sponsor so the script will be useful in the future too.

[Bibliographic note for NLM donor.xlsx](https://github.com/buda-base/library-issues/files/5239860/Bibliographic.note.for.NLM.donor.xlsx)

**Comment by xristy** [comment]
Done. @karmagongde see [https://www.tbrc.org/docs/nlm/summary-Bibliographic_note_for_NLM_donor-20200917-2020-09-18T16:18:28.69Z.txt](https://www.tbrc.org/docs/nlm/summary-Bibliographic_note_for_NLM_donor-20200917-2020-09-18T16:18:28.69Z.txt)

**Comment by karmagongde** [comment]
@xristy Hi Chris, Thank you very much for importing the donor's name in the NLM Work number. It saved lots of Librarians time. 
Best,
Karma

**Comment by karmagongde** [comment]
@xristy @JannTibetan Hi Chris, Here is another list of donor's name for the NLM scanning Project from ACIP and BDRC. This is similar to the last one. When you get time, please help to import them to the catalog records with another "Bibliographic Note Field" 
Here is a link to the list:
https://docs.google.com/spreadsheets/d/1_hTDtM9X8g9mGk5d5Ma-xEOFeTgZeUi330xtz9XZHMA/edit#gid=299780623

Thank you!

**Comment by JannTibetan** [comment]
Thank you @karmagongde and @xristy

**Comment by JannTibetan** [comment]
@xristy  @karmagongde   Are the sponsorship statements online yet? I want to show the donor that his name is actually online because it will make him happy and also encourage his Google colleagues to make donations of their own.
Thanks!
Jann

**Comment by xristy** [comment]
Ooops! I overlooked this last request. As soon as I get access to the spreadsheet I'll get it done.

Apologies

**Comment by xristy** [comment]
@karmagongde and @JannTibetan `Batch 2 is now updated. See [`summary-Bibliographic_note_for_NLM_donor-20201105-2020-11-05T18:10:01.7Z.txt`](https://www.tbrc.org/docs/nlm/summary-Bibliographic_note_for_NLM_donor-20201105-2020-11-05T18:10:01.7Z.txt)

**Comment by JannTibetan** [comment]
Thank you Chris. I'll share this with the donor this afternoon.
