### ISSUE TITLE
reimporting ttbbc spreadsheet

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#291]
This spreadsheet:

https://docs.google.com/spreadsheets/d/1rJ4B-1EpXlby8EmpX53jlFfgaZWpPOJOWYLj1nZripw/edit#gid=0

was imported but a field is wrong: the "bibliographic note" should be a "scan info"

**Comment by eroux** [comment]
sorry, false alarm, this is a migration bug

**Comment by eroux** [comment]
sorry again, there is indeed a problem, it's in the pubinfo: the biblioNote in https://www.tbrc.org/xmldoc?rid=MW0TTBBC0009 shouldn't be there, @xristy can you please remove it?

**Comment by xristy** [comment]
@eroux so you want all of the TiBET records to have the
```
<mw:biblioNote encoding="native" lang="english"/>
```
deleted?

**Comment by eroux** [comment]
yes

**Comment by xristy** [comment]
Specifically, the records `MW0TTBBC0001` - `MW0TTBBC0091`.

**Comment by eroux** [comment]
note that there's a gap at 17

**Comment by xristy** [comment]
Referring to [TTBBC RID](https://docs.google.com/spreadsheets/d/1rJ4B-1EpXlby8EmpX53jlFfgaZWpPOJOWYLj1nZripw/edit#gid=0) above I see no gap at 17?! There appear to be 91 entries numbered 01 - 91

**Comment by xristy** [comment]
Done

**Comment by eroux** [comment]
excellent, thanks!
