### ISSUE TITLE
Space instead of Tsek

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/library-issues#292]
In the following image of book Title has two minor mistake,
1) Need to remove Tsek and replace it with space(marked with red arrow).
2) Need remove both the Shad "།" and Tsek " ་ ". Replace it with space (marked with red round). [Link](https://library.bdrc.io/show/bdr:MW8LS16008?tabs=bdr:W8LS16008)

![image](https://user-images.githubusercontent.com/42564256/94637531-6c82cd80-030a-11eb-9196-4c5d190ef1a1.png)

**Comment by eroux** [comment]
thanks! It's fixed now
