### ISSUE TITLE
scanInfo value in W8LS15972

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#293]
In the data about W8LS15972 (https://www.tbrc.org/xmldoc?rid=W8LS15972) there's

```xml
<work:scanInfo>
Scanned at Tibetan Buddhist Resource Center, 1430 Massachusetts Ave, 5th Floor Cambridge, MA 02138. Comments: 01/2015
</work:scanInfo>
```

which doesn't appear on

https://www.tbrc.org/#!rid=W8LS15972

That's the first mystery. The second mystery is that this has been digitized by rKTs with a camera (not scanned, and not by BDRC). So I'm wondering where this indication comes from? This is quite a problem as it is visible on BUDA (although it's not on tbrc.org). @karmagongde what do you think of the indication that it has been scanned at TBRC? Is it something that should generally be ignored? @xristy do you know why the scanInfo doesn't appear on the website? Is it just a bug of this record or is it a general design?

**Comment by karmagongde** [comment]
@eroux During generating the scan request, there are only default options to select "scanned at TBRC or Delhi". The scanned by Mangaram are selected "Delhi" and the rest are "TBRC". In the old website, this field is not displayed. So, it avoids all the confusion and misunderstanding. Just like NLM told us the images are not scanned at TBRC, so Travis replaced all the scan requests 2 pages with blank pages (see example W1GS135531, W1KG1132). Also, many people shared their digital texts with BDRC in various formats with different types of equipment. So, this is something we should ignore.

**Comment by eroux** [comment]
ooooh ok thanks a lot! I'll ignore the data that says it's scanned at tbrc (because it doesn't say really give any information), but I think I'll keep the information that it's been scanned in Delhi, as I think this one would be accurate?
