### ISSUE TITLE
understanding scanInfo

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#294]
I'm trying to migrate the scanInfo property properly, and there seems to be a bit of digital archeology needed... 

## What the values mean

There are 4 main groups of values for the scanInfo:
- `Scanned at Tibetan Buddhist Resource Center, 1430 Massachusetts Ave, 5th Floor, Cambridge, Mass` which we established doesn't mean anything
- `Scanned at Tibetan Buddhist Resource Center, 150 West 17th St, New York City [...]` could that be accurate or is it the same as the previous one?
-  `scanned at the tibetan buddhist resource center at the rubin museum of art, 150 w 17th st.` I guess that's accurate?
- `Scanned at M/S Satluj Infotech Images, E-45, Sector 27 Noida [...]` which is accurate I think?
- `Scanned at Tibetan Buddhist Resource Center, Southwest University of Nationalities, Chengdu, China` I guess this one is accurate too? or does it just mean that Paldor created the pull request but not necessarily that the scanning happened there?

## RFP and DPL480

First, at the end of some scanInfo there are comments with `RFP #` and a number, like in [W3CN2163](https://www.tbrc.org/xmldoc?rid=W3CN2163), what does it mean? Also, in some others like [W3MS493](https://www.tbrc.org/xmldoc?rid=W3MS493) we can read `DPL480 RFP 94`, does it mean that the work is in the PL480?

(as a note, we might want to turn the PL480 works as a visible collection? that would be a good tribute to the foundation of BDRC I think)

@karmagongde @xristy what do you think?

**Comment by xristy** [comment]
The first - third values signify the address of TBRC HQ at various times. The second and third are the same location, just an immaterial change designating the affiliation with Rubin. The fourth is Mangram's scanning operation in India. I'm not sure what all is covered by the fifth, it would likely include some of Paldor's work but maybe others. @karmagongde  probably is knowing.

I'm not familiar with the rules the librarians have used for RFP & PL480 info. Fwiw, the DLMS Editor adds any comments like: `Comments: ` after the address.

We should create a PL480 collection. This has been discussed a number of times. Lauren has tried to figure out a list, queries have been done on LoC and unfortunately only scattered information has been pulled together.

We could try some forensics work if we knew the dates of PL480 funding that Gene was working with. We could look at dates in the work and pubinfo records and get an idea. 

I would guess that a bunch of the old form RIDs are PL480 materials such as [W23504](https://www.tbrc.org/#!rid=W23504) would have been part of the PL480, but there's nothing in the records other than some possible hints such as that Sanje Dorje in Delhi in 1973 published a print run from block prints. The first page of the scan input form mentions Lama Ngodrup (Dorji I think?) and Sherab Drimey in Paro in 1982, which is consistent with what I recall from a conversation w/ Gene once about some of the individuals that Gene worked w/ in the PL480 days - do take a large grain of NaCl with this. I have no idea about 1973 vs 1982 from the scan input form.

I only find 51 works with `<pubinfo:pl480/>` entries and all but one are the work of Michael Sheehy, the other is added by Karma in [MW1KG10597](https://www.tbrc.org/xmldoc?rid=MW1KG10597). I recall there was a push for a period to try and identify the PL480 works and I think Michael was may be the lead on that.

**Comment by karmagongde** [comment]
On the scan request comments: **RFP#** and **DPL480 RFP#** are related to the USAID Project images payment and both are the same. These notes are added at the beginning of the USAID Project started. Later these numbers are not available at the time of generating the scan request so there is no **RFP#** or **DPL480 RPF#** in the later work numbers for the USAID image.

As I mentioned in an earlier ticket, I am 100% sure if the images scanned at the NLM 1.0 images which have "Scanned at Tibetan Buddhist Resource Center, 1430 Massachusetts Avenue, Cambridge, MA 02138 US" they will make an issue.
Also, many individuals shared PDF, JPEG, Tiff which was not scanned at TBRC has the same Scan Info: "Scanned at Tibetan Buddhist Resource Center"

The scan request info generated by Paldor at Chengdu office are also not consistent. Since he has several machines some have "Scanned at Tibetan Buddhist Resource Center, Southwest University of Nationalities, Chengdu, China" and many have "Scanned at Tibetan Buddhist Resource Center, 1430 Massachusetts Ave, 5th Floor, Cambridge, Mass"
![Screen Shot 2020-10-01 at 1 24 50 PM](https://user-images.githubusercontent.com/19337852/94844247-f5256a80-03eb-11eb-9e18-bedba7821fd9.png)

Could you please share the Library of Congress PL480 result. Thanks!

**Comment by eroux** [comment]
Ah ok thanks! Can I remove these RFP / DPL480 indications or do you think they can be useful? It's too bad that these things are inconsistent... but well. I still have a little bit of hope for option 2 and 3...

In any case, here's the list of the PL480:

[pl480.txt](https://github.com/buda-base/library-issues/files/5313935/pl480.txt)

**Comment by eroux** [comment]
For instance W23453 (which BTW looks like a PL480 and is not in the list) is recorded as being scanned in NY... do you think it has been? Also, perhaps the works recorded as scanned in NY could be good candidates for the PL480

**Comment by xristy** [comment]
I don't think there's a distinction between 2 and 3 regarding whether the scanning actually occured in the office or not. There was a change in the address info at some point for a reason I don't remember. The address info is compiled into the editor. As Karma mentions TBRC doesn't necessarily indicate that scanning actually took place in the office. The Mass address ceased implying the scanning happened in the current office after the scanners were turned off in 2015 or 2016.

The DLMS Editor does default to _TBRC_ so the user has to specifically select either _Delhi_ or _other_ and then fill in additional scanning location info.

My 51 works were generated by a sloppy bash loop w/ grep.

I agree that W23453 looks as plausible a pl480 as W23504 which is mentioned above and is also not on the list.

It is almost certain that W23453 was actually scanned in the NY office in 2004. There were at least 2 and at times I recall 3 people operating scanners all day long as I recall.

**Comment by eroux** [comment]
hmmm ok... maybe we can reconstruct a timeline?
- year ??? TBRC moves to Cambridge
- year 2015-2016 no scanning happens in the US anymore
- year ??? the DLMS starts to be used with 3 possible values (tbrc, Delhi, other)

Also, do you think the value is reliable for pre-DLMS records?

**Comment by karmagongde** [comment]
Thank you for the PL480 list. You will see lots of them are created by Gene la, a few Chozin and Some are mine work numbers.
During cataloging, we check in LoC catalog to get LC Call Number, LCCN, and PL480. All the PL 480 texts has it's own identy number such as (i-tib1319).

In the LoC catalog records which have the PL 480 info, we add them on TBRC catalog. The text do not have PL 480 number in LoC catalog record we keep as it is.

**Comment by xristy** [comment]
I think Lauren has queried LoC for the pl480 info and the number of results were significantly less than expected. Jeff and Lauren I think have estimates of how many pl480 works there are.

The older works such as W23504 and W23453 with a second LoC page don't necessarily mean pl480 because once people had been mentored by Gene via pl480 funds, then those people in many cases continued to locate, reproduce and publish materials. So there can be old format rids for works produced in a similar time frame that aren't actually pl480 since they were produced w/o pl480 funds.

I'm sure @karmagongde and @Klhamo and Jeff have much more clarity to offer here

**Comment by eroux** [comment]
ok! @xristy  What do you think of the timeline on https://github.com/buda-base/library-issues/issues/294#issuecomment-702316675 ?

**Comment by xristy** [comment]
It should also include when the scanning ceased in Cambridge, which I don't know.

the earliest scan request record, based on log entry, in exist-db should establish the earliest date at which the dlms editor was in use.

I don't remember when the Cambridge office got up and running but the ealiest records w/ scaninfo showing Cambridge should establish the initial time for #1 and whatever Karma et al remember about when the scanning stopped in Cambridge should establish a window on #1. There was only a single person scanning in Cambridge so the production would not be nearly as great as in NYC. Since I wasn't on site I don't know if there's log somewhere of the actual scanning done in the office. Maybe @karmagongde would know of such, that would be ideal.

I would think the scan info, when present, on old records with two tbrc pages can be considered reliable

**Comment by eroux** [comment]
ah yes, thanks a lot! I'll investigate all that tomorrow

**Comment by eroux** [comment]
Here's a bit of data archeology:

- the earliest logentry in a scanrequest is in [SR00EGS1016200](https://www.tbrc.org/xmldoc?rid=SR00EGS1016200) for [W00EGS1016199](https://www.tbrc.org/xmldoc?rid=W00EGS1016199) with the value `2006-10-23T09:33:08.109Z`.
- pre-DLMS works can have the Cambridge scaninfo value in some cases such as [W22065](https://www.tbrc.org/xmldoc?rid=W22065), it is even relatively common (306 cases).
- the move to set the Cambridge address seems to date from 2013-05, despite a few earlier outliers like [SR01JW43](https://www.tbrc.org/xmldoc?rid=SR01JW43) / [W00EGS1016733](https://www.tbrc.org/xmldoc?rid=W00EGS1016733) (note that the scan request says `venue="Delhi"` so it's even more difficult to make any sense of it)

Now for the more annoying thing... doing a grep for New York indicates a few things:
- some DLMS configurations to this day are set with the NY address, see for instance [W2KG209055](https://www.tbrc.org/xmldoc?rid=W2KG209055)
- this leads to some very bizarre scanInfo values saying the CIHTS scanned books for TBRC in NY ([W2KG5033](https://www.tbrc.org/xmldoc?rid=W2KG5033))
- also the Delhi scanInfo is still set up with the NY address ([W8LS67196](https://www.tbrc.org/xmldoc?rid=W8LS67196))

Soo... where to go from there if we want the data to mean anything... hard to tell! Here are a few proposals:
- when a scanInfo contains "atluj" (meaning it's in Delhi), changing it to a hardcoded value that doesn't contain the address (keeping the comments at the end, they sometimes contain valuable information)
- ignoring everything that has Cambridge as the address (keeping just the comments)
- ignoring everything that has New York as the address and a scanrequest posterior to 2013 (again keeping the comments)

what do you think?

**Comment by eroux** [comment]
Finally, note that we don't have any scanInfo for the FPL works, for comparison we have for EAP:

```
This manuscript was digitized with the generous support of the British Library’s Endangered Archives Programme and Arcadia, a charitable fund of Lisbet Rausing and Peter Baldwin. The manuscripts were made available by the Fragile Palm Leaves Foundation.
```

@TBRC-pmench what do you think would be a good comment about the digitization of the FPL works? (something that would include the place, sponsors, etc.)

**Comment by TBRC-pmench** [comment]
"This manuscript was digitized with the generous support of Khyentse Foundation, in partnership with the Fragile Palm Leaves Foundation."

Is the location needed in this note? Isn't provenance elsewhere in the metadata?

**Comment by eroux** [comment]
I think the location of the scanning (as opposed to the location where the manuscript is) would be good yes

**Comment by TBRC-pmench** [comment]
Oh those are the same place. They're being scanned onsite. So we could say:

"This manuscript was digitized at the Fragile Palm Leaves Foundation in Thailand with the generous support of Khyentse Foundation."

**Comment by xristy** [comment]
> Now for the more annoying thing... doing a grep for New York indicates a few things:
> 
> some DLMS configurations to this day are set with the NY address, see for instance W2KG209055
> this leads to some very bizarre scanInfo values saying the CIHTS scanned books for TBRC in NY (W2KG5033)
> also the Delhi scanInfo is still set up with the NY address (W8LS67196)
> 

Ooops on my part! I had forgotten that the venue description for scan requests is a preference setting:

![Screen Shot 2020-10-02 at 10 01 52 AM](https://user-images.githubusercontent.com/3542294/94938663-c3b5a900-0496-11eb-9b31-c1be34c82ab5.png)

So for W2KG5033 evidently @karmagongde modified the "TBRC Venue Description"

This also explains why the old address is still being used for Cambridge. I thought we must have had an updated install but instead there should have been an effort to get all the editor configs updated

**Comment by xristy** [comment]
> pre-DLMS works can have the Cambridge scaninfo value in some cases such as W22065, it is even relatively common (306 cases).

Gene cataloged a bunch of his holdings well before they were scanned do to resource limitations so later scan requests were generated much later

**Comment by xristy** [comment]
> Soo... where to go from there if we want the data to mean anything... hard to tell! Here are a few proposals:
> 
> when a scanInfo contains "atluj" (meaning it's in Delhi), changing it to a hardcoded value that doesn't contain the address (keeping the comments at the end, they sometimes contain valuable information)

That seems fine. I assume that you will retain that the scanning was performed at _M/S Satluj Infotech Images in Delhi_. This is/was Mangaram's company that was established for scanning Gene's images and should be retained somehow.

> ignoring everything that has Cambridge as the address (keeping just the comments)

Well there were items actually scanned at the Cambridge office. @karmagongde should be able to help clarify here.

> ignoring everything that has New York as the address and a scanrequest posterior to 2013 (again keeping the comments)

There were 2-3 people scanning full time at the NYC office for at least 6 years, so I'm not sure why that should be ignored? @karmagongde and @Klhamo should be able to at least establish some dates here.

**Comment by eroux** [comment]
> That seems fine. I assume that you will retain that the scanning was performed at [...]

yes

> Well there were items actually scanned at the Cambridge office

yes, but afaict there's no way to know what was scanned at Cambridge and what wasn't (although I'm happy to be contradicted)

> There were 2-3 people scanning full time at the NYC office for at least 6 years

Oh you mean some people were scanning in NY even after the move to Cambridge in 2013??

**Comment by xristy** [comment]
sorry I missed the _posterior_ modifier. No. There was no scanning in NYC after the office moved to Cambridge

**Comment by Klhamo** [comment]
No were scanning in NY even after the move to Cambridge in 2012

**Comment by Klhamo** [comment]
until mid 2012,  3 people scanning in  NY  and scanning in we move to Cambridge,   then only one person scanning

**Comment by Klhamo** [comment]
until mid 2017

**Comment by Klhamo** [comment]
My apology,   scanning Cambridge stopped  2016 April

**Comment by Klhamo** [comment]
No  scanning in NY after the move to Cambridge in mid 2012
Until mid 2012, three people are scanning in NY and after we move to Cambridge, then only one person scanning until at Cambridge stopped 2016 April.


        
MAY ALL BEINGS BE HAPPY!
Kelsang Lhamo (ཆོས་འཛིན།)
Buddhist Digital Resource Center

**Comment by eroux** [comment]
excellent, this is really helpful! I'll reajust the location (Cambridge vs. NY) according to the date

**Comment by karmagongde** [comment]
@eroux Hi Elie, I am generating a scan-request for the books PDF format provided by Drepung Loseling Library, Mungod, Karnataka, India. What scan information need to show on our new website and how? 
Thanks!

**Comment by eroux** [comment]
Hi Karma! I've never really been able to run the DLMS so I don't really know how to change the value of the scanInfo, but @xristy maybe you know about that? Maybe it can be changed using the configuration given in https://github.com/buda-base/library-issues/issues/294#issuecomment-702789093 ? 

Another option would be to put the value in the comment of the scanrequest (as the first part saying "Scanned at TBRC, Cambridge, etc." will be removed), but I also don't know how the comments are generated...

Finally, if you put a biblioNote that starts with "scann" (like "scanned at", "scanning by", etc.) it will be automatically transformed into a scanInfo during the migration to the new website, that's probably the easiest option

**Comment by xristy** [comment]
@karmagongde The scan request wizard has a drop down to select TBRC or Delhi and below that is "other". Select that and just enter whatever the scan info is supposed to be for what you're doing and that should do it.

**Comment by karmagongde** [comment]
@xristy I just generated a scan request for W2KG216524 as you have suggested. Selected the "other" and add the "scan info" in the comments: Even select the "Other" in the scan request dropdown menu it shows the "Scanned at Tibetan Buddhist Resource Center, 1430 ..."

**Comment by eroux** [comment]
What you did is ok, in the migration to BUDA, only the part that says "Scanned images are made available through the kind support of Drepung Loseling Educational Society, Mundgod, Karnataka" will be migrated, not the first part. I'll show you in a few days when the next migration happens. In any case, thanks for filling this data well, I think this will be a good improvement!

**Comment by xristy** [comment]
@karmagongde Well go into the Editor preferences and select DLMS Production Manager, and erase the TBRC Venue Description:

![Screen Shot 2020-10-06 at 2 25 57 PM](https://user-images.githubusercontent.com/3542294/95250974-78760000-07e0-11eb-8386-927db5b1b85e.png)

Then just put the desired comments. The resulting element will look like:

    <work:scanInfo>Scanned at . Comments: generous support by Laibach</work:scanInfo>

That should be easily detectable during migration to BUDA

**Comment by eroux** [comment]
sure, I can add some code to spot that too

**Comment by karmagongde** [comment]
@xristy @eroux Sure, I will do that. Thank you.

**Comment by eroux** [comment]
@karmagongde thanks for setting the scaninfo of W2KG216524! Just a small request, can you phrase it so that it starts with something like "scanned at" or "scanned by", or "scans made available by"? it's just for consistency as other values are like that too... no need to change what you've done already. Thanks!

**Comment by eroux** [comment]
@xristy another quick request, can we update the scanInfo of the works in PR1PEMAKOD00 to:

```
Part of the project "Two Family Libraries from Pemako" by Robert Mayer. Material photographed in the course of 2016 by Mr Tenzin Dhonyoe, who works for the Multimedia Section of the Shantarakshita Library, Central University for Tibetan Studies. The funds were offered by Oxford University’s John Fell OUP Research Fund.
```

? Thanks!

**Comment by xristy** [comment]
All 6 works in `PR1PEMAKOD00` have been updated

**Comment by eroux** [comment]
excellent, thanks! BTW Karma the scanInfo on https://library.bdrc.io/show/bdr:W2KG216524 looks good!
