### ISSUE TITLE
Update scanInfos

### ISSUE THREAD

**Issue by xristy** [buda-base/library-issues#295]
All Works in PR1VIENNA00 should have their scanInfo replaced with 

    "Digitization by the Cultural History of the Western Himalaya-Project "Tibetan Manuscripts" (University of Vienna)"

all the W1FPL* records could have their scanInfo set to 

    "This manuscript was digitized at the Fragile Palm Leaves Foundation in Thailand with the generous support of Khyentse Foundation."

**Comment by xristy** [comment]
All 95 of PR1VIENNA00 have been updated

All 11196 of PR1FPL01 have been updated.

Note the `<w:scanInfo/>` isn't displayed on tbrc.org

**Comment by eroux** [comment]
thanks!

**Comment by eroux** [comment]
Sorry, another request on that: on the `W1NPL*` can we add this scanInfo:

```
Digitized as part of the Nepalese Buddhist Sanskrit Manuscript Scanning Initiative, a collaboration with the Nagarjuna Institute of Buddhist Studies in Kathmandu, Nepal, and with funding from University of the West and Internet Archive.
```

? Thanks! This is part of a note, if it's easy to remove it it would be fine, if not it's ok too

**Comment by xristy** [comment]
I don't find any works with RIDs matching `W1NPL*`.

**Comment by eroux** [comment]
oh, right, I forgot they exist only in BUDA sorry!
