### ISSUE TITLE
strange volumes in W4CZ7445

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#296]
we're missing some volumes in W4CZ7445, namely:
- I1KG9936
- I1KG9939
- I1KG9958
- I1KG9967

but instead of just being empty they contain the scan request images + a picture of a yellow cloth... it's really not ideal as this means we don't indicate the volumes as being absent and tease the users with the first image, but there's really nothing there. Could we remove the images in these image groups please @karmagongde @TBRC-Travis ? Thanks!

**Comment by karmagongde** [comment]
@eroux A note of missing volumes is already on the catalog record. Users will know the missing volumes from it.

@TBRC-Travis Could you please remove empty volumes I1KG9936, I1KG9939, I1KG9958, and I1KG9967 from the website.
Thank you!
![Screen Shot 2020-10-04 at 2 43 14 PM](https://user-images.githubusercontent.com/19337852/95024319-4e8dd380-0650-11eb-94bd-b4848b8d3e55.png)

**Comment by eroux** [comment]
ok thanks! I think removing the one image in each volume will make for a better user experience, especially on BUDA

**Comment by karmagongde** [comment]
@TBRC-Travis Also, please remove the empty volumes no. 36, 46, 75, 85 from **W1PD127393**, - I1PD127495, I1PD127505, I1PD127534, and I1PD127544. Thanks.

**Comment by TBRC-Travis** [comment]
@eroux @karmagongde I've removed the empty image groups for W4CZ7445.  

On tbrc.org they're showing up as expected now ("Page images not yet available for this Volume") but on library.bdrc.io they display with a "loading manifest..." message which obviously never loads:

![image](https://user-images.githubusercontent.com/19354126/95343419-80887b00-0886-11eb-8d71-66947371da64.png)

**Comment by eroux** [comment]
thanks! I'll take a look at the "loading manifest..." thing

**Comment by karmagongde** [comment]
@TBRC-Travis @eroux I checked with vol. no. 69 and looks fine. [Images not yet available.] Please see the screenshot.

![Screen Shot 2020-10-07 at 10 26 18 AM](https://user-images.githubusercontent.com/19337852/95344576-c98cff00-0887-11eb-83b6-73396652df91.png)

**Comment by TBRC-Travis** [comment]
@karmagongde well we're both right.  if you access the volume through the "extended properties" view then it brings up the page as you said.  but if you go through the IIIF browser and scroll down to the volume it shows up as I said.  :)

**Comment by eroux** [comment]
reported on https://github.com/buda-base/public-digital-library/issues/289 , closing this issue. Thanks again!

**Comment by TBRC-Travis** [comment]
> @TBRC-Travis Also, please remove the empty volumes no. 36, 46, 75, 85 from W1PD127393, - I1PD127495, I1PD127505, I1PD127534, and I1PD127544. Thanks.

@karmagongde I've removed the empty volumes from W1PD127393 as well.

**Comment by karmagongde** [comment]
@TBRC-Travis  Thank you, Travis.
