### ISSUE TITLE
PL480 PublisherName list 

### ISSUE THREAD

**Issue by karmagongde** [buda-base/library-issues#298]
@xristy @eroux @JannTibetan 
Dear Chris and Elie,

Here are the publisher's names who have published Tibetan texts from 1965 to 1985. The listed names are according to the printed names on the texts. The publishers used various different spellings and formats and the listed names are from our PublisherName metadata and I kept all as it is.

I know there are missing books of PL480 in our collection. When we get a complete list of PL480 from some universities. I can check and find the missing books and try to get them from other libraries.

Could you please pull all the **work numbers** with **titles** and **publication information** for the following PublisherName? So, I can doublecheck them based on book shape, preface etc. and we can make PL480 collection those are available in BDRC collection. 

b. jamyang norbu
bir tibetan society
Campa Chogyal
chime namgyal
chopal lama
chophel legdan
chos 'phel legs ldan
choten
d. g. khochen tulku
d. g. khochhen trulku
d. gyaltsen
d. gyaltshan & kesang legshay
d. t. tashigang
d. tsondu senge
d. tsondru sengge
d. tsondu senghe
d.w. tashigang
Dam chos smon lam
damchoe monlam
damchoe sangpo
dasho sherub
distributor, tibetan bonpo monastic center
dodrup chen rimpoche
dodrup sangyey lama
don 'grub rdo rje
don-grub-rdo-rje
dondup tashi
drug sherig press
dupjung lama
g.t.k. lodoy and n. gyaltsan
g.t.kunga lodoy and n. gyaltshan
getse tulku kundgalodoy
gonpo tsetan lama
gonpo tseten
jamyang samten and tashi
janser tenzin
jurme drakpa
kalsang lhundup
kandro
kargyud sungrab nyamso khang
karma chophel
kesang thabkhes
khasdub gyatsho shashin
khedup gyatso
shashin
Konchhg Lhadrepa
kun bzang stobs rgyal/
kunsang tobgey
kunsang topgay
kunsang topgyel and mani dorje
kunsang topgyel and mani dorji
lama dawa
lama dawa & sherab gyaltsen
lama dawa and chopal lama
lama guru deva
lama ngodrup and sherab demy
lama ngodrup and sherab drimey
lippa
lopon tenzin namdak
mani dorji
mgon-po-tshe-brtan
mongolian lama guru deva
n. gyaltsen
n. lungtok & n. gyaltsen
n. sopa
ngag dbang bzod pa
ngawang gelek demo
ngawang sonam
ngawang sopa
Ngawang Tenzin
ngawang topgyay
ngawang topgyel
ngawang topgye
ngodrup and sherab drimey
ngodrup lama
ngodup
orgyan dorji
p.l. sonam gyaltsen
Patshang Lama Sonam Gyaltsen
patshang lama sonam gyaltsen
pema gyaltsen
pema lodoe
rta-rna bla-ma
s.w. tashigangpa
sanje dorje
sherab drimay
sherab gyaltsen and lama dawa
sherab gyaltsen lama
shes rab rgyal mtshan/
sonam dakpa
sonam gyaltsen
sonam rabten
sonam t. kazi
sonam topgay kazi
sonam w. tashigang
t. 'jam-dbyangs
t. g. dhongthog
t. g. dhongthog rinpoche
t. sonam tashigang
t. tsepal taikhang
T. Tsepal Taikhang
t.s. tashigang
tango monastic community
tashi dorji
tau pon
tibetan bonpo monastic center
tibetan bonpo monastic community
tibetan nyingmapa monastery
tinley jatso
trinley jamtsho
trinley jamtso
tobdan tsering
tondup tashi
topga tulku
trayang
trayang and jamyang samten
tsering dorma gelek
tsering paljor emchi
tsering paljor emchi
tshering dargye
tshering wangyal
tshultrim Tashi
Tsultrim Tashi
tsondu senghe
tulku kunsang gyatso
tulku pema lodoe
ugyen tempai gyaltsen
urgyan dorji
urgyan dorje

Thank you,
_____________
Karma Gongde | Head Librarian 
ནང་བསྟན་དཔེ་ཚོགས་ལྟེ་གནས། | 佛教数字资源中心 
Buddhist Digital Resource Center
www.bdrc.io

**Comment by eroux** [comment]
Here's a list of works that have the names you mention as publisherName:

[potentialPL480.csv.zip](https://github.com/buda-base/library-issues/files/5469269/potentialPL480.csv.zip)

It has 627 entries. I've checked that it doesn't have any of the works already identified as pl480 in https://github.com/buda-base/library-issues/issues/294#issuecomment-702298463

**Comment by eroux** [comment]
Ideally we could record the PL480 identifier for all these, it could be done in the spreadsheet directly

**Comment by karmagongde** [comment]
@eroux Thank you, this list is very helpful. If it is not too much work, could you please add the publisher date/year in this list. This will help us to make more accurate PL480 books based on the publications date/year. Some of the publisher might have published books after the period (1965-1985) of the PL480.

Also, could you please pull all the work numbers which has PL 480 with the publisher name and date. For instant, W4CZ2193 is not a PL 480 but librarian has marked as PL 480. So, I will review and correct accordingly. Thank you.

**Comment by eroux** [comment]
ah, right, I'll compile that tomorrow

**Comment by eroux** [comment]
here's the list of PL480 we have in our database, with publisher and publisher date:

[pl480.zip](https://github.com/buda-base/library-issues/files/5477259/pl480.zip)

**Comment by karmagongde** [comment]
Thank you for the list of the publisher and publication date. This will help us more accurate PL480 texts and very potential PL480 texts. I found a few of them are not PL480 rather it is an Overseas acq no. in the LoC catalog. For instant, W00EGS1017345.
Cross-checking with Publication date and Publishers will help to identify a more accurate list of PL480.

**Comment by eroux** [comment]
great! here's the list of works by the publishers you listed, with the publication date, without the ones with a pl480 in our database:

[allpubsfromlistnopl4802.zip](https://github.com/buda-base/library-issues/files/5477628/allpubsfromlistnopl4802.zip)

**Comment by eroux** [comment]
P.S.: just as a note, I think W23616 is also in PL480, even though the publisher is not in the list

**Comment by karmagongde** [comment]
@eroux It looks like W23616 is also a part of PL480. 

Also, publisher "Ngodrup and Sherab Drimay" (Drimay with a) name missed in the previous list. Please add. 

I checked both the PL480 potential list and found some "publisher names" and some dates won't some under the "PL480" publisher names and time range. So please remove them.
Under pl480.zip list:
W00EGS1017214	bhu tib 473	"dept. of education royal govt. of bhutan"	1985
W00EGS1017196	i e tib 10	a myes rma chen bod kyi rig gzhung zhib 'jug khang /	1993
W1KG21958	i tib 2605	aogen sheza	1984
W21953	i-tib-2553	aogen sheza	1984
W1KG21996	i tib 2565	bod gzhung shes rig pa khang /	1987
W21499	i-tib-3093	bod kyi dpe mdzod khang /	1992
W4CZ2193	i-tib-2009-306940; 03; 09-03	bod kyi gtsug lag zhib 'jug khang /	2009
W23834	i-tib-3114	bokar ngedon choekhor ling monastery	1993
W23179	i-tib-3077	d. tsondu senghe	1992
W23896	i-tib 3082	d. tsondu senghe	2000
W29577	i-tib-3135	d.l. tashigang	1989
W16484	i-tib-2619	drepung loseling library society	
W21963	i-tib-3089	drikung kargyu institute	1991
W29250	i-tib2187	international academy of indian culture	1981
W29468	i-tib-2985	international academy of indian culture	
W29210	bhu-tib-497	jamyang lhendrup	1994
W27921	i-tib-3081	konchhog lhadrepa	1993
W00EGS1017357	ch-tib-15	krung go'i bod kyi shes rig dpe skrun khang /	1991
W27919	i-tib-2420	library of tibetan works & archives	1983
W23161	i-tib-2522	library of tibetan works & archives	1984
W23558	i-tib-3045	library of tibetan works & archives	1988
W23806	i-tib-2590	library of tibetan works and archives	1984
W23808	i-tib2607	library of tibetan works and archives	1985
W24011	i-tib-2877	library of tibetan works and archives	1985
W23184	i-tib-3072	library of tibetan works and archives	1987
W24046	i-tib-3042	library of tibetan works and archives	1987
W1KG12130	i-tib-3056	library of tibetan works and archives	1988
W24890	i-tib-3052	library of tibetan works and archives	1989
W1GS45961	i-tib-3057	library of tibetan works and archives	1991
W00EGS1017331	bh-tib-494	padma tshewang	1991
W8473	i-tib-3159	pal-lden sakya'i-sung-rab book publishers	1989
W8455	i-tib-2747	sakya students' union	1985
W2CZ8055	i tib 2514	sakyapa students' union	1983
W23603	i-tib-2972	samdrup tshering	2002
W22379	i-tib-3943	tibetan cultural printing press	1989
W23562	n-tib-6739	tritan norbutse bon education centre	1990
W23557	n-tib-6745	tritan norbutse bonpo education centre	1990
W00EGS1017345	i tib 2986	yuthok institute of tibetan medicine	1988

Under allpubsfromlistnopl4802.zip list:
W3CN15684	Konchhg Lhadrepa	1990
W23177	d. tsondu senghe	1992
W22123	kargyud sungrab nyamso khang	1997
W22124	kargyud sungrab nyamso khang	1997
W1KG12279	d. tsondu senghe	1998
W23437	kargyud sungrab nyamso khang	2001
W23683	kargyud sungrab nyamso khang	2002

**Comment by eroux** [comment]
Thanks! I've updated the lists to these:

[pl480lists.zip](https://github.com/buda-base/library-issues/files/5687884/pl480lists.zip)


I've removed the ones you listed and added these:

- W20578,Ngodrup and Sherab Drimay,1976-1980,
- W23819,Ngodrup and Sherab Drimay,1979,
- W23727,Ngodrup and Sherab Drimay,1984,
- W6460,Ngodrup and Sherab Drimay,1980,
- W21826,Ngodrup and Sherab Drimay,1977-1981,
- W23623,Ngodrup and Sherab Drimay,1978,
- W1KG9728,Ngodrup and Sherab Drimay,1979,
- W6468,Ngodrup and Sherab Drimay,,
- W9366,Ngodrup and Sherab Drimay,1979,
- W22136,sherab drimay,1983
- W9366,t.s. tashigang,1979,
- W21560,t.s. tashigang,1979,
- W23875,t.s. tashigang,1979,
- W21562,t.s. tashigang,1979,
- W23616,taklung tsetrul rinpoche pema wangyal,1982
- W23712,ngodrup,1976
- W5062,sonam topgay kazien,,
- W6460,,1980,
- W1KG12152,ugyen tempai gyaltsen,1979,
- W3916,ngodup,1975-1994,
- W21947,ngodrub and sherab demy,1978,
- W1KG11906,lama dodrup sangyay,1977,
- W22642,lama pema tashi,1982-1986,
- W23946,lama ngodru and sherab demy,1982,
- W3904,d.g. khochhen tulku,1977,
- W27923,d.g. khochhen tulku,1976,
- W1KG9673,sherab demy,1983,
- W1KG12138,lama ngodrup and sherab demy,1982,
- W23206,dodrup sangye lama,1976,
- W27915,dodrup sangye lama,1979,
- W24029,ngodrup and sherab demy,1978,
- W6489,lama ngodrub and sherab drimed,1983,
- W22917,lama ngodrub and sherab demy,1979,
- W24120,lama ngodrub and sherab drimey,1982,
- W21947,ngodrub and sherab demy,1978,
- W26033,ngodrub and sherab demy,1978,
- W24039,lama ngodrub and sherab demy,1979,
- W1KG22087,ngodrub and sherab demy,1978,
- W00KG09391,b. jamyang norbu,1971
- W20867,b. jamyang norbu,1972
- W30100,b. jamyang norbu,1971
- W18,b. jamyang norbu,1977
- W00KG09353,b. jamyang norbu,1972
- W30348,b. jamyang norbu,1972
- W00KG09351,b. jamyang norbu,1971
- W24309,s. w. tashigangpa,1972

I've also tried to search some publisher names on BUDA which has a more lenient search than the strict match that I did and I think there's a lot more to add to the lists... for instance those on [this random seach](https://library.bdrc.io/search?q=%22tashigangpa%22&lg=en&t=Instance&f=asset,inc,tmp:hasOpen&n=44)

I'm also unsure about

W20876,lama ngodrub and sherab drimey,1982

(it's probably one but it doesn't have the nice preface)

**Comment by eroux** [comment]
I'm wondering if W8LS73683 might be PL480 too?

**Comment by karmagongde** [comment]
According to the publisher's name and year, W20876 should be a part of the PL480. But this set does not have the preface as other PL480 texts. Many times there are two sets before publishing as a sample and actual published texts. I still believe this is a part of PL480. I will look for the set which has a preface.

W8LS73683 is definitely a part of PL480.

**Comment by eroux** [comment]
I think now is a good time to create the collection, @xristy I've created PR1PL480, could you add it to the following list of works?

[pl480list.zip](https://github.com/buda-base/library-issues/files/6166260/pl480list.zip)

For reference, here's a list that I've added today:
- W00EGS1016284
- W19664
- W30138
- W1GS2162
- W30136
- W29912
- W1KG12690
- W23739
- W30139
- W00EGS1016267
- W23771
- W30134

**Comment by xristy** [comment]
990 Works added to PR1PL480

**Comment by eroux** [comment]
Thanks a lot! This is pretty impressive!
