### ISSUE TITLE
cataloging printeries

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#301]
Hi @karmagongde ,

In order to import the TiBET / TTBBC catalog, it would be helpful to add the following missing places. I try to present them below in a form that should make it easier to catalog, but the original file is [here](http://booksdb.socanth.cam.ac.uk:8080/exist/apps/TTBBC/data/refsources/places.xml). You can find a bit of information in [this article](https://www.researchgate.net/publication/321084772_17_An_Unacknowledged_Revolution_A_Reading_of_Tibetan_Printing_History_on_the_Basis_of_Gung_thang_Colophons_Studied_in_Two_Dedicated_Projects) or in *Early Buddhist Block Prints from Mang-Yul Gung Thang* (Erhard, 2000), which I unfortunately don't have...

Thanks!

#### 1

- type: hidden valley (hidden land ?)
- main name: sbas yul skyid mo lung
- note: on the Tibet-Nepal border

#### 2

- type: hermitage
- main name: chab rom phug
- located in: mang yul gung thang
- note: near the village of rud, further south of kun gsal sgang po che
- note: chab rom phug is a hermitage established by btsun pa chos legs as one of his retreat places. chos dbang rgyal mtshan also moved there in 1511. See Ehrhard (2000) p. 24

#### 3

- type: printery
- main name: chab rom phug
- located in: chab rom phug

#### 4

- type: palace?
- main name: khams gsum g.yul las rnam rgyal
- other name: khams gsum rnam rgyal
- located in: mang yul gung thang
- note: It is a castle established by king kun dga' rnam rgyal lde in the area of skyid grong and is associated with the bo dong pa scholar chos dbang rgyal mtshan. See Ehrhard (2000) p. 31-33 and Erhard (2004) p. 139

#### 5

- type: printery
- main name: khams gsum g.yul las rnam rgyal pho brang
- located in: khams gsum g.yul las rnam rgyal

#### 6

- type: printery
- main name: mdzo lhas
- located in: mang yul gung thang
- note: It was probably situated on the banks of the dpal khud mtsho, not far from chos sdings. See Ehrhard (2000) p. 60-61.

#### 7

- type: valley(?)
- main name: la 'debs
- other name: la 'de
- other name: lan dhe
- other name: lan de

#### 8

- type: printery
- main name: a ti sha'i chos 'khor
- located in: la 'debs

**Comment by karmagongde** [comment]
@eroux I will create records for the listed place and printery names.

**Comment by eroux** [comment]
excellent, thanks!

**Comment by karmagongde** [comment]
@eroux Here are the Place record numbers. For the Printery names added "par khang /"
G2KG220149 = sbas yul skyid mo lung /
G2KG220150 = chab rom phug
G2KG220151 = chab rom phug gi par khang /
G2KG220152 = khams gsum g.yul las rnam rgyal /
G2KG220153 = khams gsum g.yul las rnam rgyal gyi par khang /
G2KG220154 = mdzo lhas par khang /
G2KG220155 = la 'debs/
G2KG220156 = a ti sha'i chos 'khor par khang /

**Comment by eroux** [comment]
excellent, thanks!
