### ISSUE TITLE
works about themselves

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#304]
@karmagongde there are two works that are "isCommentaryOf" of "isInstanceOf" themselves:
- W8LS16303
- W1KG1625

I'm not sure what this actually means but I think there might be better ways to encode it? This creates some bogus display on BUDA so I'm thinking maybe we could change these? Thanks!

**Comment by karmagongde** [comment]
@eroux Just corrected both the work numbers with the right conceptual work number.

**Comment by eroux** [comment]
excellent, thanks a lot!
