### ISSUE TITLE
titles with wrong lang tags

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#306]
@karmagongde while extracting the titles from the database I spotted a few titles tagged with the wrong language:
- in W1KG23517 there's an English title tagged as Chinese
- in W2PD16797 there's a Tibetan titles tagged as Chinese

**Comment by karmagongde** [comment]
@eroux Just fixed the language and encoding of both the work numbers.

**Comment by eroux** [comment]
thanks!
