### ISSUE TITLE
updating scaninfo for works scanned in China

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#307]
we should update the scanInfo of these works:

[china-rids.txt](https://github.com/buda-base/library-issues/files/5477647/china-rids.txt)

to:

`Scanned or acquired in Tibetan areas of China by BDRC`

**Comment by xristy** [comment]
Out of 2414 entries in the list, the scanInfo for 2369 Works were updated.

There were 45 works that contained extraneous content, mostly in the form of an appended "-\dv" or "-V\d" etc:

[china-rids-spurious.txt](https://github.com/buda-base/library-issues/files/5477979/china-rids-spurious.txt)

**Comment by eroux** [comment]
Ah excellent, thanks! I didn't notice those... could you update it also for

W3CN22971
W3CN23000
W3CN25663
W3CN25679
W3CN25735

? (They're a cleaned up version of the list of broken ones)

**Comment by xristy** [comment]
The 5 Works have been updated

**Comment by eroux** [comment]
great, thanks!
