### ISSUE TITLE
updating scanInfo

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#314]
Hi @xristy could you update the scaninfo for those RIDs:

- W2KG217488
- W2KG217489
- W2KG217490
- W2KG217491
- W4CZ301881
- W3CN2862
- W4CZ301800
- W4CZ301723
- W4CZ301801
- W4CZ301802
- W4CZ301803
- W4CZ301724
- W4CZ301804
- W4CZ301805
- W4CZ301806
- W4CZ301807
- W4CZ301809
- W4CZ301810
- W4CZ301812
- W4CZ301725
- W4CZ301813
- W4CZ301814
- W4CZ301816
- W4CZ301815
- W4CZ301818
- W1KG13838
- W4CZ301819
- W4CZ301820
- W4CZ301821
- W4CZ301822
- W4CZ301823
- W4CZ301727
- W4CZ301824
- W4CZ301728
- W4CZ301825
- W4CZ301826
- W4CZ301827
- W4CZ301828

to

```
Images from the DVDs of "bod kyi shing spar lag rtsal gyi byung rim mdor bsdus bzhugs so (A brief introduction to the history of Tibetan printing technology)", Paltsek, 2013
```

? Thanks!

**Comment by xristy** [comment]
All 38 works updated

**Comment by eroux** [comment]
excellent, thanks!
