### ISSUE TITLE
identifying / creating a few author records

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#318]
Hi @karmagongde ,

I'm exploring the import of the [Leiden collection](https://digitalcollections.universiteitleiden.nl/tibetantexts), we have a catalog here:

https://docs.google.com/spreadsheets/d/1BwC9snBK-od6GUM61E10IiDGWJuTSKrw5S1VbDfrqGc/edit#gid=925539164

and I'm working on identifying some of the authors (not all, which would be too much work). There are a few authors that I can't find in our database though. I think for those 7 authors with associated dates we should either find some match or create a record:

- mati śīla (1745-1800), maybe a translation of "blo gros tshul khrims"? associated works:
   * [ka lnga par 'jug pa'i smon tshig mgyogs 'gro'i pho nya zhes bya ba dang rdza rtsig gi gtam rgyud bcas](http://hdl.handle.net/1887.1/item:345649), [copy 2](http://hdl.handle.net/1887.1/item:352918), [copy 3](http://hdl.handle.net/1887.1/item:339690)
   * [yongs kyi dge ba'i bshes gnyen chen po blo bzang tshul khrims kyi rtogs pa brjod pa dad ldan re skong nor bu'i do shal zhes bya ba](http://hdl.handle.net/1887.1/item:346196), [copy 2](http://hdl.handle.net/1887.1/item:350674)

- dge slong bstan 'dzin (1748-1813), associated works:
   * [dge ldan bka' brgyud rin po che'i bka' srol phyag rgya chen po rtsa 'grel rnams kyi 'grel bshad mchog mthun dngos grub kyi bang mdzod ces bya ba](http://hdl.handle.net/1887.1/item:341101)
   * [lam zab mo bla ma lha'i rnal 'byor nyams su len tshul dngos grub kun 'byung zhes bya ba](http://hdl.handle.net/1887.1/item:298830)
   * [slob dpon dpa' bos mdzad pa'i skyes rabs so bzhi pa'i 'grel bshad dad pa'i rin chen 'dren pa'i shing rta zhes bya ba](http://hdl.handle.net/1887.1/item:325620)
   * [dga' ldan lha brgya ma'i khrid yig mdor bsdus](http://hdl.handle.net/1887.1/item:309477)

- dam chos nyi ma'i sdes (1768-1822), associated works:
   * [bcom ldan rnam par rgyal ma bsnyen cing stong mchod 'bul ba'i cho ga'i lag len gsal bar khrigs bsdebs 'dod pa'i dngos grub 'dren pa'i shing rta zhes bya ba](http://hdl.handle.net/1887.1/item:314860)
   * [bde mchog lha bcu gsum ma'i dkyil 'khor dang 'brel ba'i rab gnas yan lag bzhi pa'i chog 'khrigs gsal bar bkod pa bde legs grub pa'i rgya mtsho zhes bya ba](http://hdl.handle.net/1887.1/item:308465)
   * [lha nyer gnyis ma'i rjes gnang mtshams sbyor nyung 'thus su bkod pa gzhan phan mchog sbyin ces bya ba](http://hdl.handle.net/1887.1/item:292888)

- dad pa mkhan po thugs rje (1770-1835), associated works:
   * [grub chen smra ba ser pos mdzad pa'i rtag bstod zhes bya ba bzhugs so](http://hdl.handle.net/1887.1/item:338195)
   * [gsang sngags kyi bslab bya btus pa](http://hdl.handle.net/1887.1/item:323224)
   * [rje btsun sengge'i sgra dang phyag rdor la brten pa'i sa bdag gdon 'grol byed tshul gdung sel nor bu'i zla ba zhes bya ba'i lag len chog sgrigs yang gsal](http://hdl.handle.net/1887.1/item:298677)

- dbyil gyi bston pa (born in 1175), associated work:
   * [dbal gsas drag po sku rdzogs kyi gzhung](http://hdl.handle.net/1887.1/item:312985)

- dge slong bsod snyoms pa rin chen mang thos blo gsal bstan skyong (born in 1804), associated work:
   * [bu ston lugs kyi gtor ma'i cho ga 'khrul med rab gsal gyi rnam bshad 'dod rgu 'byung ba'i dpag bsam snye ma zhes bya ba](http://hdl.handle.net/1887.1/item:310762)

- gu ru rnon rtse (born in 1136), associated work:
   * [ma rgyud thugs rje nyi ma'i bskangs bshags](http://hdl.handle.net/1887.1/item:342343)

What do you think?

**Comment by eroux** [comment]
Sorry, I found a few possible matches based on the dates, but I'm not entirely sure:
- dge slong bstan 'dzin (1748-1813) = P308
- dam chos nyi ma'i sdes (1768-1822) has the same dates as P846 and P6899 but neither of them has a similar name, so it's probably another person?
- dad pa mkhan po thugs rje (1770-1835) could be P2063 but I'm not sure...?

**Comment by karmagongde** [comment]
@eroux Here is BDRC person RID. Two of the author's record is not yet created. I will create it and send it to you. 
P311 = mati śīla (1745-1800), maybe a translation of "blo gros tshul khrims"
P308 = dge slong bstan 'dzin (1748-1813)
P846 = dam chos nyi ma'i sdes (1768-1822)
P2063 = dad pa mkhan po thugs rje (1770-1835)
P857 = dge slong bsod snyoms pa rin chen mang thos blo gsal bstan skyong (born in 1804)

**Comment by karmagongde** [comment]
@eroux 
P2KG220180 = gu ru rnon rtse (born in 1136)
P2KG220181 = dbyil gyi ston pa (born in 1175)

**Comment by eroux** [comment]
great, thanks a lot!

**Comment by eroux** [comment]
Here's another batch, these only have centuries. We have some of these works (but not all it I think), but they don't have associated authors:

- dge slong spong ba rdo rje'i ming can (1720-1803) : same dates as P333 but different name:
   * [lha chos dang mi chos 'brel ba'i bslab bya nor bu'i 'phreng ba](http://hdl.handle.net/1887.1/item:300218)
   * ['phags pa spyan ras gzigs kyi bstod pa po bstod kyi 'grel ba don yod rdo rjes mdzad pa](http://hdl.handle.net/1887.1/item:326467)

- mitri munīndra (19th century):
   * [bslab bya gzhan phan snying nor](http://hdl.handle.net/1887.1/item:298618)
   * [mi chos bslab bya dbang rtul nyer mkho](http://hdl.handle.net/1887.1/item:324182)

-  ye shes seng ge (12th century):
   * [mthu stob dbang phyug rje btsun rwa lo tsA ba'i rnam par thar pa kun khyab snyan pa'i rnga sgra](http://hdl.handle.net/1887.1/item:348206)

-  dge legs dpal bzang (19th century):
   * [ma cig khros nag sde lnga'i bdag mdun bum gsum dbang chog dang cas pa bsam 'phal dbang rgyal dngos grub 'grub pa'i gter mdzod](http://hdl.handle.net/1887.1/item:331722)
   * [gnyan khrod yig chung gsal ba'i sgron me](http://hdl.handle.net/1887.1/item:307720)
   * [ma cig zhi ba lam zab kyi dmigs khrid gsal ba'i sgron mea](http://hdl.handle.net/1887.1/item:299442)

- karma chos dbang kun bzang nges don bstan 'dzin (19th century):
   * ['phags pa bcu gcig zhal dpal mo lugs dang 'brel ba'i smyung gnas sgrub pa'i cho ga thugs rje chen po'i dgongs rgyan lag tu len tshul gyi zur rgyan rin chen drwa ba](http://hdl.handle.net/1887.1/item:321214)

- jam dbyangs chos kyi rgyal mtshan (19th cent):
   * [log rtog me sngags 'joms byed legs bshad lung gi bdud rtsi nyam nga'i mun pa sel ba'i snang](http://hdl.handle.net/1887.1/item:302297)

- dge slong dznyA na srI (19th century):
   * [bsam pa lhun grub ma'i don nyams su len tshul thugs rje'i bum bzang zhes bya ba bzhugs](http://hdl.handle.net/1887.1/item:350216)

- snyon pa shes rab dbang ldan (19/20th century):
   * [snyan rgyud a gsal gyis phri las](http://hdl.handle.net/1887.1/item:351545)

- kun bzang 'jig med tshe dbang nor bu (19th cent):
   * [bla ma'i thugs sgrub bar chad kun sel las rig 'dzin dzam gling rgyan gcig gi dbang gi cho ga indra nI la'i chun po](http://hdl.handle.net/1887.1/item:298290)

- shes rab seng ge (12th century):
   * [gshen po rang don gyi bskangs ba](http://hdl.handle.net/1887.1/item:323892)

- mi tra bha dra (16th Century):
   * [rtsis kyi bstan bcos nyin byed gsar pa bzhugs](http://hdl.handle.net/1887.1/item:331768)

- blo bzang bstan 'dzin rgyal mtshan (ca 18th century):
   * [dus gsum sangs rgyas kun gyi bdag nyid rje btsun thams cad mkhyen gzigs chen po blo bzang dpal ldan ye shes dpal bzang po'i gsang rnam gyi sgo nas gsol ba 'debs tshul](http://hdl.handle.net/1887.1/item:298316)

- mchog grub dpal 'bar bzang po (18th century):
   * [gu ru drag po dmar chen me lce'i 'phreng ba'i las byang chog khrigs bdud las rgyal ba'i rdo rje](http://hdl.handle.net/1887.1/item:313526)

- gter ston khyung po dpal dge (ca. 11th century):
   * [shin tu gnyan pa ma mo'i khrag mdos](http://hdl.handle.net/1887.1/item:297688)

- sgrub khang sprul ming (18th century):
   * [myur byon gsol 'debs 'dren mchog thugs rje bskul ba'i sgra dbyangs](http://hdl.handle.net/1887.1/item:349190)

- ngag dbang grags pa (ca. 15th cent):
   * [byang chub lam gyi rim pa nas 'byung ba'i nyams len gyi sgo rnam par nges pa legs gsungs kun gyi nying khu](http://hdl.handle.net/1887.1/item:295039)

- shAkya dbang phyug kun dga' rgyal mtshan (16th century):
   * [man ngag snying po bsdus pa bzhugs](http://hdl.handle.net/1887.1/item:1648007)

- rin chen rgya mtsho blo gros dpal bzang po (14th century):
   * [bcom ldan 'das mgon po tshe dang ye shes dpag tu med pa zhes bya ba'i 'khrid 'chi med grub pa bzhugs pa'i dbu phyogs lags so](http://hdl.handle.net/1887.1/item:327853)

- bstan 'dzin phun tshogs dbang ldan (19th century):
   * ['dir 'khor ba'i nyes dmigs dang thar pa'i phan yon mthong thos nges 'byung skye ba nor bu'i 'phreng ba](http://hdl.handle.net/1887.1/item:330390)

- rgyal ba'i myu gu mkhyen brtse'i lha (18th century): (could this be P314 ?)
   * [bde ba can du bgrod pa'i cho ga dpag med myur lam zhes bya ba dang bde ba can gyi zhing bkod smon lam](http://hdl.handle.net/1887.1/item:327837)

**Comment by karmagongde** [comment]
@eroux Hi Elie, For most of them, I added #P record. Some are not the actual names.
    • P333 = dge slong spong ba rdo rje'i ming can (1720-1803) 
    • P2181 = mitri munīndra (19th century):
    • P3147 = ye shes seng ge (12th century):
    • P2KG220183 = dge legs dpal bzang (19th century):
    • P2KG220184 = karma chos dbang kun bzang nges don bstan 'dzin (19th century):
    • P2KG220185 =  'jam dbyangs chos kyi rgyal mtshan (19th cent):
    • dge slong dznyA na srI (19th century): [Note: This volume has lots of other texts and the first one is by P675 works]
        ◦ bsam pa lhun grub ma'i don nyams su len tshul thugs rje'i bum bzang zhes bya ba bzhugs 
       
    • snyon pa shes rab dbang ldan (19/20th century):
        ◦ snyan rgyud a gsal gyis phri las
    • P2713 = kun bzang 'jig med tshe dbang nor bu (19th cent):
    • shes rab seng ge (12th century):
        ◦ gshen po rang don gyi bskangs ba
    • mi tra bha dra (16th Century):
        ◦ rtsis kyi bstan bcos nyin byed gsar pa bzhugs
    • P10726 = blo bzang bstan 'dzin rgyal mtshan (ca 18th century):
    • P2677 = mchog grub dpal 'bar bzang po (18th century):
    • P2KG220182 = gter ston khyung po dpal dge (ca. 11th century):
    • sgrub khang sprul ming (18th century):
        ◦ myur byon gsol 'debs 'dren mchog thugs rje bskul ba'i sgra dbyangs
    • P1846 = ngag dbang grags pa (ca. 15th cent):
    • P438 = shAkya dbang phyug kun dga' rgyal mtshan (16th century):
    • P2556 = rin chen rgya mtsho blo gros dpal bzang po (14th century):
    • bstan 'dzin phun tshogs dbang ldan (19th century): [Note: he is publisher]
        ◦ 'dir 'khor ba'i nyes dmigs dang thar pa'i phan yon mthong thos nges 'byung skye ba nor bu'i 'phreng ba
    • P695 = rgyal ba'i myu gu mkhyen brtse'i lha (18th century):

**Comment by eroux** [comment]
excellent, thanks a lot!
