### ISSUE TITLE
possible duplicate

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#319]
A use is wondering if P1397 and P10638 might be the same person. @karmagongde what do you think?

**Comment by karmagongde** [comment]
@eroux I checked both the biography and looks different. Anyway many of the works associated with P1397 and selected P10638 and I changed all of them. Both the titles and Teachers are different. P10638 is associated only with W30416.

**Comment by eroux** [comment]
thanks a lot!

**Comment by eroux** [comment]
reopening the issue with new developments and questions from the scholar (who specializes on the history of Minyak): W2PD20096 (now assigned P1397) contains W30416 (the only work assigned to P10638), and W2PD20096  has many referenced to Minyak. So it seems P1397 is probably a duplicate of P10638 after all. What do you think?

Also, he was wondering where the note in P1397 was coming from? as it doesn't seem to come from image 426 of W3CN18495

**Comment by karmagongde** [comment]
@eroux Could you please ask the scholar to share a few references to Minyak in W2PD20096. It will help and save my time looking for those references. And please thank him for pointing out the issue.

The note in P1397 came from W3CN18495 image number 428. 426 is before adding the 2 pages of Biblio introduction pages.
[W3CN18495-I3CN19904-428-428-any.pdf](https://github.com/buda-base/library-issues/files/5659875/W3CN18495-I3CN19904-428-428-any.pdf)

**Comment by eroux** [comment]
Sure! here's the answer

W2PD20096 PDF p 173 contains the autobiograpby of Minyag 'jam dbyangs grags pa. It is the same text as the one edited by Minyag thub sbtan chos dar under the ref W30416. This text contains several references to Minyag. In the manuscript edition, page 177 L6 the blama from Rati (G3785) then a major Monastery in Minyag is mentioned.
Thub bstan chos dar dbu can's edition is easier to search, and from it seems likley thay 'jam dbyangs grags pa was the abbot of Lhamo rste, an important monastery in Darmdo area.

Thanks you very much for the reference for the note on figure P1397! Indeed looking at p428 it seems to match.

**Comment by eroux** [comment]
@karmagongde what do you think?

**Comment by karmagongde** [comment]
@eroux Sorry, since you gave incorrect PDF page number 173 instead of 193, it took time to figure out to find whether these two are the same or different person. 

Earlier, I did not find it because of the incorrect page number. Today, I spend more time and found there are the same. 
Therefore, I am withdrawing P10638 in favor of P1397.

**Comment by eroux** [comment]
Excellent, thanks a lot!
