### ISSUE TITLE
improvements in translators' data

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#320]
here's a duplicate spot by a scholar in Hamburg: P4CZ10547 and P3731 are the same person

**Comment by eroux** [comment]
here's also part of a foonote from a forthcoming book by Dr Almogi:

> Note that Khe’u brgad Yon tan dpal is dated by the BDRC (P4CZ10522) ca.
> eighth century, but considering the bibliographical records in the rGyan
> gyi nyi ’od (and some later/modern Tibetan sources, all of which list
> him under the Later Period), this dating is clearly unlikely. [...]
> speaks for a floruit in the later part of the second half of the
> eleventh and first half of the twelfth centuries.

**Comment by eroux** [comment]
@karmagongde would you have time to look at this?

**Comment by eroux** [comment]
@karmagongde what do you think? If you don't have time to dive in the litterature, maybe we can just trust the person who reported it?

**Comment by karmagongde** [comment]
I checked P4CZ10547 and P3731 and look the same person. In P4CZ10547, the incorrect teacher date 13th cent. is selected. Therefore, I will withdraw P4CZ10547 in favor of P3731. In the future, please ask for a reference source so, it will be easier for me to look and make changes any needed.

**Comment by karmagongde** [comment]
@eroux It looks like the author is in Tengyur and assumed early year 8th cent. without actual source. Could you please ask for a reference source date of P4CZ10522 in rGyan gyi nyi ’od (and some later/modern Tibetan sources, all of which list
him under the Later Period). So, I can add on the Person Record. Thank you.

**Comment by karmagongde** [comment]
@eroux I changed the year of P4CZ10522 to 11 century based on the modern author's source. I will add the citation from Dr. Almogi's book after it is published.

**Comment by eroux** [comment]
Excellent, thanks a lot!

**Comment by eroux** [comment]
@karmagongde FYI: https://www.bibliaimpex.com/index.php?p=sr&format=fullpage&Field=bookcode&String=9783945151082&Book=Authenticity%20and%20authentication:%20glimpses%20behind%20the%20scenes%20of%20the%20formation%20of%20the%20Tibetan%20Buddhist%20canon

**Comment by karmagongde** [comment]
@eroux Thanks, I added a note on P4CZ10522.
