### ISSUE TITLE
W1KG12670 unable to build zip or pdf on buda

### ISSUE THREAD

**Issue by TBRC-TimB** [buda-base/library-issues#322]
I have been talking with a user for the past few days who has been having issues with downloading this particular work. When Travis and I looked into it, we found that neither of us could get the site to generate a pdf or zip for us. The work still works on tbrc.org so for now we are redirecting the user there.

**Comment by eroux** [comment]
thanks! moved to https://github.com/buda-base/public-digital-library/issues/406
