### ISSUE TITLE
Adding donor's names on NLM Work numbers

### ISSUE THREAD

**Issue by karmagongde** [buda-base/library-issues#323]
@xristy Hi Chris, Here is another list of donor's names for the NLM scanning Project from ACIP. When you get time please help to import them to the catalog records with another "Bibliographic Note Field". Thank you.

Here is a link to the list:
https://docs.google.com/spreadsheets/d/1dvIVllpCnV5BXpo1aO7CevsSNfDOnPgyJqGwqCKpoTc/edit#gid=231003007

**Comment by xristy** [comment]
Thanks. I probably won't get to it today, but I've got all the data.

**Comment by xristy** [comment]
The records have been updated. See [summary-Bibliographic_note_for_NLM_donor-20201223-2020-12-23T21:31:39.676Z](https://www.tbrc.org/docs/nlm/summary-Bibliographic_note_for_NLM_donor-20201223-2020-12-23T21:31:39.676Z.txt)

**Comment by karmagongde** [comment]
@xristy Hi Chris, Thank you very much for importing Donor's names. All looks perfect.
I wish you very happy holidays!!!
Karma
