### ISSUE TITLE
two volumes inverted for W1KG13126

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#329]
currently in W1KG13126 we have:
- vol 77 = I1KG13250 (= dzu)
- vol 81 = I1KG13246 (= bu)

which seems wrong and I think should be fixed to

- vol 77 = I1KG13246 (= bu)
- vol 81 = I1KG13250 (= dzu)

but the logentry says

```xml
<entry when="2019-04-26T16:00:27.239Z" who="Karma Gongde">switched volume number 77 and 81 in volumemap</entry>
```

so it seems to have been done on purpose... @karmagongde do you remember why the two volumes were inverted?

**Comment by TBRC-Travis** [comment]
@eroux we addressed this is in a previous issue.  please see #234

**Comment by eroux** [comment]
hmm ok but I guess we also didn't really address it as the two volumes are still in the wrong order... if there's no planned change (like some sync that hasn't been done yet?), I propose we just switch the two volumes in the volume map without changing the images.

**Comment by karmagongde** [comment]
Now the volumes are in the right order on tbrc.org.

**Comment by eroux** [comment]
excellent, thanks @karmagongde !
