### ISSUE TITLE
migrating T1814 to a conceptual work?

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#332]
Hi @karmagongde having T1814 as a topic is a bit counter intuitive as in similar cases we tend to have a conceptual work instead... perhaps we could migrate it? Do you think there are other cases like this we could migrate too?

**Comment by karmagongde** [comment]
@eroux T1814 used for particular Dorje Drolo teaching revealed by Yongde Migyur Dorjee. 

There are many #T related to deities that have the same case because of traditional linage or Terton. So, please migrate all of them.

**Comment by karmagongde** [comment]
@eroux T1814 used for particular Dorje Drolo teaching revealed by Yongde Migyur Dorjee.

There are many #T related to deities that have the same case because of individual lineage teaching or Terton's revealed teaching. So, please migrate all of them.

**Comment by eroux** [comment]
ok I see, if it's really a lineage and not a work let's keep it that way. Thanks!
