### ISSUE TITLE
closing etext viewer should bring back to etext instance page

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#333]
for instance, go to

https://library.bdrc.io/show/bdr:IE0OPP008105

unfold volume 1 in outline, click on "open in viewer", it leads to https://library.bdrc.io/show/bdr:UTIE0OPP008105_v001#open-viewer (which is quite reasonable)

but then when clicking on "close etext", it leads to https://library.bdrc.io/show/bdr:UTIE0OPP008105_v001 which is not where we were before, it's quite confusing... In case differentiating the two contexts is a bit of work, close etext could always lead to the etext instance page instead of the etext ref page

**Comment by berger-n** [comment]
fixed
closing etext volume now returns to etext outline:

![image](https://user-images.githubusercontent.com/33383857/107258573-400b5a80-6a3c-11eb-81cf-c6331bf1ba6a.png)

**Comment by eroux** [comment]
perfect, thanks a lot!
