### ISSUE TITLE
persons students of themselves

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#338]
In these records the persons are students of themselves, which breaks the BUDA UI (for good reasons):

- [x] P745
- [x] P8297
- [x] P8224
- [x] P2642
- [x] P1646

in the case that I've looked at, it's because P8224 is marked as being a student of P3835, but then P3835 has been withdrawn in favor of P8224. I suspect this is the case for the other persons

see https://github.com/buda-base/public-digital-library/issues/433

**Comment by karmagongde** [comment]
@eroux I fixed the Person records that have withdrawn #P record and students of themselves.

I did not find it for P8297.

**Comment by eroux** [comment]
Thanks @karmagongde ! The case of P8297 is a bit different, he's directly a student of himself, see in https://www.tbrc.org/xmldoc?rid=P8297 :

```xml
<p:studentOf pid="P8297"> 'jam dpal dgyes pa'i rdo rje </p:studentOf>
```

**Comment by karmagongde** [comment]
@eroux I fixed it. Thank you.

**Comment by eroux** [comment]
excellent, thanks!
