### ISSUE TITLE
Image download problems with W1FEMC****** works

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/library-issues#342]
Trent reported that he has been unable to download files from Cambodia works. I tested a few works and had issues as well.

1. https://library.bdrc.io/show/bdr:W1FEMC030140 — generating the PDF from the IIIF viewer never completed. The progress % would increase and decrease, and +45 minutes later still would not finish
2. https://library.bdrc.io/show/bdr:W1FEMC010933 — downloading PDF and Zip from the record completed. Downloading from the IIIF viewer did not work.
3. https://library.bdrc.io/show/bdr:W1FEMC010934 — downloading worked.
4. https://library.bdrc.io/show/bdr:W1FEMC030141 — generating the PDF got to 96% and then reset to 0%, restarted and worked. Generating the PDF in the IIIF viewer got to 99% and reset to 0%. Generating the Zip worked after a while but when I tried to download I got a 502 Bad Gateway error.
![image](https://user-images.githubusercontent.com/48484924/110671650-c7afca80-819c-11eb-9c83-75276c1c28cf.png)

**Comment by eroux** [comment]
thanks! I've moved it to https://github.com/buda-base/buda-iiif-server/issues/71
