### ISSUE TITLE
collection of texts from the gNas bcu lha khang

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#344]
I've created a collection for texts coming from the gNas bcu lha khang (PR1NCLK) so that we can keep track of the scans we have of:
- scans of texts from the collection directly
- scans of reprints, either facsimile or input (mostly by Paltsek)

The ones we currently have are:
- direct scans:
   * W8LS15749
   * W26453 (this one has an unusual history and doesn't appear in the catalog by Paltsek)
   * W3JT13602
   * W3JT13588
   * W3JT13587
   * W3JT13586
   * W3JT13585
   * W3JT13584
   * W3JT13603
   * W3JT13589
   * W4CZ301807
   * W4CZ301809
   * W4CZ301810
   * W4CZ301812
   * W4CZ301819
   * W4CZ301821
   * W4CZ301822
   * W2CZ6598
   * W2CZ7692
   * W1KG13616
   * W4CZ301827
   * W4CZ301723
   * W4CZ301802
   * W4CZ301724
   * W4CZ301725
   * W4CZ301726
   * W4CZ301727
   * W2KG217487
   * W1KG15058
   * W1KG15057
   * W1KG15059
   * W1KG15060
   * W1PD90416
   * W1KG15061 (?)
 - reproductions of texts coming from Drepung (sometimes mixed with other texts):
   * W1PD89051
   * W1PD153536
   * W1PD89084
   * W1GS66332
   * W1PD77570
   * W1PD153537
   * W1PD180878
   * W1KG10687
   * W1KG14303
   * W1AC375
   * W1KG14335
   * W3CN8060
   * W3PD1288
   * W3PD287
   * W4PD3075
   * W4PD3076
   * W00EGS1017426
   * W1GS66286 (?)
   * W2DB25060 (?)
   * W1PD104698 (?)

@karmagongde any comment ? (do you see something I might have forgotten or something like that?) If not, @xristy can you put all of these in PR1NCLK ?

**Comment by JannTibetan** [comment]
Fantastic, thanks. Let’s add the reference Ducher’s article in the notes section for the overall collection. 
Cécile Ducher, “Goldmine of Knowledge: The Collections of the Gnas bcu lha khang in ’Bras spungs Library,” Revue d’Etudes Tibétaines, no. 55, Juillet 2020, pp. 121–139.

**Comment by karmagongde** [comment]
Among the list, the following work numbers are computer input texts. Neither reprints nor facsimile. Should we really want to add it under PR1NCLK? When the reprints or facsimile of these texts are available then we can add them under PR1NCLK. 

I checked the W1KG14303 and W1AC375 and found the sources materials are from various places such as Drepung, Palpung, Drug Tashi Chosdzong, and so on) see: _bsdu sgrig gsal bshad_ p.no.5.
W1KG14303 
W1AC375 (Drepung, Palpung, Drug Tashi Chosdzong, Potala, Nepal, and other foreign countries) see: _bsdu sgrig gsal bshad_ p.no.5-6.
W1KG14335
W3CN8060
W3PD1288
W00EGS1017426

**Comment by eroux** [comment]
Yes, let's keep these, see this extract from Cécile Ducher's article:

![1](https://user-images.githubusercontent.com/60868/111188294-346c0000-85b5-11eb-887e-0727a9a5e89f.png)

it's still interesting that most of the originals are from Drepung specifically

**Comment by eroux** [comment]
BTW, the article says there are 400 volumes of Kagyu material published by Paltsek in the 2010s but only cites 158... perhaps the list could be completed in that regard

**Comment by eroux** [comment]
@karmagongde I added a few more entries but for some I'm not totally sure they are from Drepung:
- W1KG15061 really looks like W1KG15060 which is indicated as being from Drepung
- W1GS66286
- W2DB25060
- W1PD104698

what do you think about these?

**Comment by karmagongde** [comment]
@eroux  As you said, W1KG15061 Looks like the same as W1KG15060 even there is no mark of _phyi_ or _nang_ and some of the title " ཕྱག་རྒྱ་ཆེན་པོ་ལྔ་ལྡན་སྟན་ཐོག་གཅིག་མ་བདུད་རྩིའི་འོད་ཟེར།" is not inside the Drepung catalog. In W1KG15060, there are many titles with  _phyi_ or _nang_.
As before, other work numbers are the input of Drepung Library, Palpung and other. Besides the percentage ratio, these modern published books can be added under PR1NCLK.

**Comment by eroux** [comment]
ok, thanks a lot! let's not add W1KG15061 then and let's add the others. @xristy would you have time to put all the following RIDs in the PR1NCLK product?

```
W8LS15749
W26453
W3JT13602
W3JT13588
W3JT13587
W3JT13586
W3JT13585
W3JT13584
W3JT13603
W3JT13589
W4CZ301807
W4CZ301809
W4CZ301810
W4CZ301812
W4CZ301819
W4CZ301821
W4CZ301822
W2CZ6598
W2CZ7692
W1KG13616
W4CZ301827
W4CZ301723
W4CZ301802
W4CZ301724
W4CZ301725
W4CZ301726
W4CZ301727
W2KG217487
W1KG15058
W1KG15057
W1KG15059
W1KG15060
W1PD90416
W1PD89051
W1PD153536
W1PD89084
W1GS66332
W1PD77570
W1PD153537
W1PD180878
W1KG10687
W1KG14303
W1AC375
W1KG14335
W3CN8060
W3PD1288
W3PD287
W4PD3075
W4PD3076
W00EGS1017426
W1GS66286
W2DB25060
W1PD104698
```

**Comment by xristy** [comment]
53 Works added to PR1NCLK

**Comment by eroux** [comment]
excellent, thanks a lot!

**Comment by eroux** [comment]
@xristy a few things appeared from emptiness and can be classified in PR1NCLK:
- W8LS17391
- W8LS17030
- W8LS17031
- W8LS17032
- W8LS17390
- W8LS17392
- W8LS17399
- W8LS17400
- W8LS17401
- W8LS17410
- W8LS17411
- W8LS17416
- W8LS17419
- W8LS17420

could you add them? Thanks!

**Comment by xristy** [comment]
14 Works added

**Comment by eroux** [comment]
excellent, thanks a lot!
