### ISSUE TITLE
title of W1KG1680

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#345]
I just received a report from a user saying that the bibliographical title of W1KG1680 shouldn't be 'brug gi rgyal rabs because the book by P7800 (of which we have two copies) is the more famous book with that name, and it's not really a name that appears in W1KG1680. @karmagongde what do you think?

**Comment by karmagongde** [comment]
@eroux That suggestion is correct. I removed the title 'brug gi rgyal rabs. Thanks!

**Comment by eroux** [comment]
great, thanks!
