### ISSUE TITLE
RIDs to be added to the Lokesh Chandra collection

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#348]
doing a search on BUDA I found the following that should be added to PR1LOKESH01:
- W8LS66716
- W1KG13683
- W30268
- W29227
- W1KG10237
- W30182
- W29571
- W22106
- W7494
- W30450
- W30451
- W4CZ7933
- W22737
- W14322
- W29228
- W30155
- W29227
- W30151
- W19357
- W30131
- W30285
- W22914
- W30135
- W1KG14782
- W7667
- W1KG13683
- W1KG6113
- W4CZ5370

(note that some may already be in the collection). @xristy would you have time to take a look?

**Edit:** I removed the RIDs that were in PR1LOKESH01 already

**Comment by xristy** [comment]
28 Works added to PR1LOKESH01

**Comment by eroux** [comment]
thanks!
