### ISSUE TITLE
gender oddities

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#353]
Hi @karmagongde there are a few errors in P1PD108247:
- P1PD108249 was his father, not his mother as indicated
- P938 was his uncle and not his brother, according to my friend who studies the Shangpa lineage

**Comment by eroux** [comment]
Actually I realize that the query for this case is quite easy, here's a list of persons indicated as male and also as mothers:

- [ ] P3726
- [ ] P6849
- [ ] P3544
- [ ] P1372
- [ ] P1477
- [ ] P3562
- [ ] P7764
- [ ] P1565
- [ ] P4982
- [ ] P2025
- [ ] P4520
- [ ] P2215
- [ ] P2216
- [ ] P2216
- [ ] P2166
- [ ] P8427
- [ ] P6906
- [ ] P3647
- [ ] P1250
- [ ] P1610
- [ ] P3689
- [ ] P2035
- [ ] P1379
- [ ] P2106
- [ ] P1412

and female fathers:

- [ ] P10489
- [ ] P10489
- [ ] P4723

Note that P938 doesn't appear in these lists because it doesn't have a gender... so just in case, here are the records following the same pattern (mother, no gender):

- [ ] P2JM24
- [ ] P2JM490
- [ ] P1CN46340
- [ ] P2JM327
- [ ] P2JM169
- [ ] P1TD10
- [ ] P1PD108249
- [ ] P3JM2
- [ ] P3JM18
- [ ] P3JM97
- [ ] P2JM367
- [ ] P8LS4265
- [ ] P2JM509
- [ ] P2JM472
- [ ] P2JM310
- [ ] P2MS9527
- [ ] P2JM446
- [ ] P2JM400
- [ ] P1KT6
- [ ] P2JM269
- [ ] P3JM87
- [ ] P2JM469
- [ ] P2JM17
- [ ] P2JM27
- [ ] P2JM7
- [ ] P2JM139
- [ ] P3JM99
- [ ] P3JM99
- [ ] P8LS4266
- [ ] P2JM441
- [ ] P3JM94
- [ ] P3JM68

**Comment by karmagongde** [comment]
Added gender to all of them, except P2MS9527. It does not look like a Person's name and it is an orphan there is no way to find the source.
Regarding P10489, there is no associate kinship, so how it could be female fathers?

**Comment by eroux** [comment]
Thanks a lot! 

P10489 is an interesting case as it's one where the migration improved the data. If you look at https://library.bdrc.io/show/bdr:P10489 you'll see that it has three kinship relations: P10487 P10488 and P977. They are not indicated in the record of P10489 but they are indicated in these other records. The migration normalizes all that. 

Same for P2MS9527 actually, it has a kinship relation on BUDA but not on tbrc.org. So perhaps in general it would be good to look at BUDA to determine if a record is orphan or not, because if we reuse a record that we determine to be orphan by inspecting tbrc.org (which I still think we shouldn't in any case at all), we might confuse non-orphan records with orphan records...

**Comment by karmagongde** [comment]
These two are very strange situations. I checked out the Person record in DLMS and did not find any Kinship.
I will fix the situation with P10489. 
After checking the father of Dudjomlinpa P705, I will make a correction to P2MS9527.

**Comment by karmagongde** [comment]
Okay done.

**Comment by eroux** [comment]
great, thanks!
