### ISSUE TITLE
duplicate outline node IDs

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#36]
This is an issue similar to #22, some outlines contain duplicate node IDs:

- [x] `O1AT2` contains several nodes with ID `O1AT21AT280`
- [ ] `O1PD181215` contains several nodes with ID `O2DB757124CZ175793`
- [ ] `O8LS26362` contains several nodes with ID `O8LS263628LS26976`
- [ ] `O2DB102429` contains several nodes with ID `O2DB1024292DB102435`

**Comment by karmagongde** [comment]
Could you please send with the title of the text. It will be easy and time saving for us to look into outlines. Thank you.

**Comment by eroux** [comment]
- `O1AT21AT280` has titles
  - `gsang ba'i lung bstan me bya yan gyi bstan pa gso thabs//`
  - `drag po gnam lcags 'bar ba'i mtshon cha dgra dpung 'joms pa'i bshan dmar//`
- for `O2DB757124CZ175793` the whole section appears twice (with all subnodes) and has title `skabs gnyis pa/ 'bras bu sngags kyi theg pa'i skor/  (ka-lu)`
- `O8LS263628LS26976` has titles
  - `bai dkar dgongs don gshin rtsis 'khyer bder gces par btus pa phan bde'i dpal 'byed rin chen lde mig`
  - `gnam chos thugs kyi gter kha lasH rtsa gsum spyi'i gtor bsngos/`
- `O2DB1024292DB102435` has titles
  - `bkra shis lhun po gsar du bzhengs pa'i rgyu rkyen/`
  - `paN chen sku phreng bcu pa blo bzang 'phrin las lhun grub chos kyi rgyal mtshan gyi rnam thar mdor bsdus/`
