### ISSUE TITLE
W8LS2027 request to make available and OCR

### ISSUE THREAD

**Issue by nh36** [buda-base/library-issues#60]
W8LS20272 hPha ran sir nyar ba'i tun hong yig rnying shog dril gyi bshus yig phyogs bsgrigs

This text is a transliteration of Dunhuang documents. As the documents themselves are in the public domain and the transliteration is a mechanical exercise that does not involve a creative act, it is likely this work cannot be copyrighted, so can be make unrestricted on the BDRC's site. 

Also, I request that the text is OCRed for searching in the etext collection as this would be of substantial research value to Old Tibetan studies.

**Comment by xristy** [comment]
The correct RID is [W8LS20272](https://www.tbrc.org/#!rid=W8LS20272).

**Comment by eroux** [comment]
Thanks for the report! The item is correctly marked as Public Domain, but also has a "temporarily restricted" access, which means we don't provide access to the images for a few years after the publication of the work. This kind of copyright issue is currently being discussed at BDRC, we should come up with an updated policy soon. As a note, the introduction is under copyright.

**Comment by eroux** [comment]
moved to https://github.com/OpenPecha/ocr-wishlist/issues/1
