### ISSUE TITLE
Withdrawn lists

### ISSUE THREAD

**Issue by karmagongde** [buda-base/library-issues#67]
@xristy @eroux 
Dear Chris and Elie,
Could you please make lists of all the Withdrawn 1. Work number, 2. Outline, 3. Person record, 4. Topic, 5. Place, As well as list of Onhold work numbers and Conceptual Work numbers  and send to me.
Same time, please make another list of each withdrawn Topic, person and place  which are still referenced/associated with any work numbers or outlines. We will concentrate on these records and make sure no data will be lost.
**Please filtered TLM work records and Person records with you make the list. We are not touching these records.**
This will help us to clean-up and after we have finished clean-up. Please completely delete withdrawn stuff from DLMS or other source. So that, withdrawn stuff will never be used again.
There are some new topics which are not in Taxonomy. We will add them later.
This will also help during emerge our Data to next platform. 
Thank you,
Karma

**Comment by eroux** [comment]
This is a very good idea! We'll work on that and hopefully have something next week (once the Chinese mirror is in a satisfying state).

**Comment by eroux** [comment]
@karmagongde do you still need this?
